; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG139587 DB	'Ui::wsimulation', 00H
$SG151025 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG151026 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG151027 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154026 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG154027 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154028 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154387 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG154388 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154389 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154748 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG154749 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154750 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG155602 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG155603 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG155604 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_wsimulation@@3Uqt_meta_stringdata_wsimulation_t@@B DD 0ffffffffH ; qt_meta_stringdata_wsimulation
	DD	0bH
	DD	00H
	ORG $+4
	DQ	00000000000000c0H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000b4H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000000afH
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	0000000000000098H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000098H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000092H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000086H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000082H
	DB	077H
	DB	073H
	DB	069H
	DB	06dH
	DB	075H
	DB	06cH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	053H
	DB	06fH
	DB	06cH
	DB	076H
	DB	065H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	DB	00H
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	050H
	DB	06fH
	DB	069H
	DB	06eH
	DB	074H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	DB	055H
	DB	070H
	DB	064H
	DB	061H
	DB	074H
	DB	065H
	DB	049H
	DB	06eH
	DB	066H
	DB	06fH
	DB	072H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	053H
	DB	06fH
	DB	06cH
	DB	076H
	DB	065H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	069H
	DB	06eH
	DB	067H
	DB	050H
	DB	06fH
	DB	069H
	DB	06eH
	DB	074H
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	00H
	DB	043H
	DB	068H
	DB	065H
	DB	063H
	DB	06bH
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	069H
	DB	06eH
	DB	067H
	DB	050H
	DB	06fH
	DB	069H
	DB	06eH
	DB	074H
	DB	00H
	ORG $+3
?qt_meta_data_wsimulation@@3QBIB DD 08H			; qt_meta_data_wsimulation
	DD	00H
	DD	00H
	DD	00H
	DD	06H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	01H
	DD	03H
	DD	02cH
	DD	02H
	DD	06H
	DD	03H
	DD	00H
	DD	033H
	DD	02H
	DD	06H
	DD	04H
	DD	00H
	DD	034H
	DD	02H
	DD	0aH
	DD	05H
	DD	00H
	DD	035H
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	036H
	DD	02H
	DD	08H
	DD	07H
	DD	01H
	DD	037H
	DD	02H
	DD	08H
	DD	02bH
	DD	06H
	DD	03H
	DD	06H
	DD	02H
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	01H
	DD	02H
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@wsimulation@@UEBAPEBUQMetaObject@@XZ ; wsimulation::metaObject
PUBLIC	?qt_metacast@wsimulation@@UEAAPEAXPEBD@Z	; wsimulation::qt_metacast
PUBLIC	?qt_metacall@wsimulation@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; wsimulation::qt_metacall
PUBLIC	?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; wsimulation::qt_static_metacall
PUBLIC	?clickedSolveButton@wsimulation@@QEAAXNIN@Z	; wsimulation::clickedSolveButton
PUBLIC	?clickedStartPointButton@wsimulation@@QEAAXXZ	; wsimulation::clickedStartPointButton
PUBLIC	?staticMetaObject@wsimulation@@2UQMetaObject@@B	; wsimulation::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?UpdateInformation@wsimulation@@QEAAXXZ:PROC	; wsimulation::UpdateInformation
EXTRN	?SolveButton@wsimulation@@AEAAXXZ:PROC		; wsimulation::SolveButton
EXTRN	?StartingPointButton@wsimulation@@AEAAXXZ:PROC	; wsimulation::StartingPointButton
EXTRN	?CheckStartingPoint@wsimulation@@AEAAX_N@Z:PROC	; wsimulation::CheckStartingPoint
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
EXTRN	__security_cookie:QWORD
EXTRN	_fltused:DWORD
_BSS	SEGMENT
?staticMetaObject@wsimulation@@2UQMetaObject@@B DB 030H DUP (?) ; wsimulation::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@wsimulation@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@wsimulation@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@wsimulation@@UEAAPEAXPEBD@Z DD imagerel $LN8
	DD	imagerel $LN8+136
	DD	imagerel $unwind$?qt_metacast@wsimulation@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@wsimulation@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@wsimulation@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN24
	DD	imagerel $LN24+628
	DD	imagerel $unwind$?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?clickedSolveButton@wsimulation@@QEAAXNIN@Z DD imagerel $LN3
	DD	imagerel $LN3+124
	DD	imagerel $unwind$?clickedSolveButton@wsimulation@@QEAAXNIN@Z
$pdata$?clickedStartPointButton@wsimulation@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$?clickedStartPointButton@wsimulation@@QEAAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@wsimulation@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@wsimulation@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@wsimulation@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@wsimulation@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@wsimulation@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0620eH
$unwind$?qt_metacall@wsimulation@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0c217H
$unwind$?clickedSolveButton@wsimulation@@QEAAXNIN@Z DD 012919H
	DD	0a21aH
	DD	imagerel __GSHandlerCheck
	DD	040H
$unwind$?clickedStartPointButton@wsimulation@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@wsimulation@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@wsimulation@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'wsimulation::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 121
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@wsimulation@@2UQMetaObject@@B, rax
; Line 122
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_wsimulation@@3Uqt_meta_stringdata_wsimulation_t@@B
	mov	QWORD PTR ?staticMetaObject@wsimulation@@2UQMetaObject@@B+8, rax
; Line 123
	lea	rax, OFFSET FLAT:?qt_meta_data_wsimulation@@3QBIB
	mov	QWORD PTR ?staticMetaObject@wsimulation@@2UQMetaObject@@B+16, rax
; Line 124
	lea	rax, OFFSET FLAT:?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; wsimulation::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@wsimulation@@2UQMetaObject@@B+24, rax
; Line 125
	mov	QWORD PTR ?staticMetaObject@wsimulation@@2UQMetaObject@@B+32, 0
; Line 126
	mov	QWORD PTR ?staticMetaObject@wsimulation@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@wsimulation@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'wsimulation::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?clickedStartPointButton@wsimulation@@QEAAXXZ PROC	; wsimulation::clickedStartPointButton
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 171
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 172
	xor	r9d, r9d
	mov	r8d, 1
	lea	rdx, OFFSET FLAT:?staticMetaObject@wsimulation@@2UQMetaObject@@B ; wsimulation::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 173
	add	rsp, 40					; 00000028H
	ret	0
?clickedStartPointButton@wsimulation@@QEAAXXZ ENDP	; wsimulation::clickedStartPointButton
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 32
__$ArrayPad$ = 64
this$ = 96
_t1$ = 104
_t2$ = 112
_t3$ = 120
?clickedSolveButton@wsimulation@@QEAAXNIN@Z PROC	; wsimulation::clickedSolveButton
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 164
$LN3:
	movsd	QWORD PTR [rsp+32], xmm3
	mov	DWORD PTR [rsp+24], r8d
	movsd	QWORD PTR [rsp+16], xmm1
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 165
	mov	QWORD PTR _a$[rsp], 0
	lea	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	lea	rax, QWORD PTR _t2$[rsp]
	mov	QWORD PTR _a$[rsp+16], rax
	lea	rax, QWORD PTR _t3$[rsp]
	mov	QWORD PTR _a$[rsp+24], rax
; Line 166
	lea	r9, QWORD PTR _a$[rsp]
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@wsimulation@@2UQMetaObject@@B ; wsimulation::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 167
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 88					; 00000058H
	ret	0
?clickedSolveButton@wsimulation@@QEAAXNIN@Z ENDP	; wsimulation::clickedSolveButton
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
tv142 = 36
tv156 = 40
_t$1 = 48
result$2 = 56
$T3 = 64
$T4 = 80
_o$ = 112
_c$ = 120
_id$ = 128
_a$ = 136
?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; wsimulation::qt_static_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 88
$LN24:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H
; Line 89
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 90
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 92
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 5
	ja	$LN12@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN23@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN6@qt_static_:
; Line 93
	mov	eax, 8
	imul	rax, rax, 3
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movsd	xmm0, QWORD PTR [rax]
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	movsd	xmm1, QWORD PTR [rcx]
	movaps	xmm3, xmm0
	mov	r8d, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?clickedSolveButton@wsimulation@@QEAAXNIN@Z ; wsimulation::clickedSolveButton
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 94
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?clickedStartPointButton@wsimulation@@QEAAXXZ ; wsimulation::clickedStartPointButton
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 95
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UpdateInformation@wsimulation@@QEAAXXZ	; wsimulation::UpdateInformation
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 96
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?SolveButton@wsimulation@@AEAAXXZ	; wsimulation::SolveButton
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 97
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?StartingPointButton@wsimulation@@AEAAXXZ ; wsimulation::StartingPointButton
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 98
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?CheckStartingPoint@wsimulation@@AEAAX_N@Z ; wsimulation::CheckStartingPoint
$LN12@qt_static_:
$LN2@qt_static_:
; Line 101
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN13@qt_static_
; Line 102
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 105
	lea	rax, OFFSET FLAT:?clickedSolveButton@wsimulation@@QEAAXNIN@Z ; wsimulation::clickedSolveButton
	mov	QWORD PTR $T3[rsp], rax
	mov	DWORD PTR $T3[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN18@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN17@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T3[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN18@qt_static_
$LN17@qt_static_:
	mov	DWORD PTR tv142[rsp], 1
	jmp	SHORT $LN19@qt_static_
$LN18@qt_static_:
	mov	DWORD PTR tv142[rsp], 0
$LN19@qt_static_:
	cmp	DWORD PTR tv142[rsp], 0
	je	SHORT $LN14@qt_static_
; Line 106
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
; Line 107
	jmp	$LN1@qt_static_
$LN14@qt_static_:
; Line 112
	lea	rax, OFFSET FLAT:?clickedStartPointButton@wsimulation@@QEAAXXZ ; wsimulation::clickedStartPointButton
	mov	QWORD PTR $T4[rsp], rax
	mov	DWORD PTR $T4[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T4[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN21@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN20@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T4[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN21@qt_static_
$LN20@qt_static_:
	mov	DWORD PTR tv156[rsp], 1
	jmp	SHORT $LN22@qt_static_
$LN21@qt_static_:
	mov	DWORD PTR tv156[rsp], 0
$LN22@qt_static_:
	cmp	DWORD PTR tv156[rsp], 0
	je	SHORT $LN15@qt_static_
; Line 113
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 1
$LN15@qt_static_:
$LN13@qt_static_:
$LN5@qt_static_:
$LN1@qt_static_:
; Line 118
	add	rsp, 104				; 00000068H
	ret	0
	npad	3
$LN23@qt_static_:
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; wsimulation::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@wsimulation@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; wsimulation::qt_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 146
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 147
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 148
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 149
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 150
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 151
	cmp	DWORD PTR _id$[rsp], 6
	jge	SHORT $LN5@qt_metacal
; Line 152
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@wsimulation@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; wsimulation::qt_static_metacall
$LN5@qt_metacal:
; Line 153
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 6
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 154
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 155
	cmp	DWORD PTR _id$[rsp], 6
	jge	SHORT $LN7@qt_metacal
; Line 156
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 157
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 6
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 159
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 160
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@wsimulation@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; wsimulation::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv77 = 32
this$ = 64
_clname$ = 72
?qt_metacast@wsimulation@@UEAAPEAXPEBD@Z PROC		; wsimulation::qt_metacast
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 136
$LN8:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 137
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 138
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_wsimulation@@3Uqt_meta_stringdata_wsimulation_t@@B+192
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 139
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 140
	lea	rdx, OFFSET FLAT:$SG139587
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN4@qt_metacas
; Line 141
	cmp	QWORD PTR this$[rsp], 0
	je	SHORT $LN6@qt_metacas
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 48					; 00000030H
	mov	QWORD PTR tv77[rsp], rax
	jmp	SHORT $LN7@qt_metacas
$LN6@qt_metacas:
	mov	QWORD PTR tv77[rsp], 0
$LN7@qt_metacas:
	mov	rax, QWORD PTR tv77[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN4@qt_metacas:
; Line 142
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 143
	add	rsp, 56					; 00000038H
	ret	0
?qt_metacast@wsimulation@@UEAAPEAXPEBD@Z ENDP		; wsimulation::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@wsimulation@@UEBAPEBUQMetaObject@@XZ PROC	; wsimulation::metaObject
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 131
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 132
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@wsimulation@@2UQMetaObject@@B ; wsimulation::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 133
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@wsimulation@@UEBAPEBUQMetaObject@@XZ ENDP	; wsimulation::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 176
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xsimulationwidget.cpp
; Line 176
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
