; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG418012 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
$SG416627 DB	'x == d', 00H
	ORG $+5
$SG418013 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG418014 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG426215 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG426216 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG426217 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG418381 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG418382 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG418383 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG426638 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG426639 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG426640 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG427061 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG427062 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG427063 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG419224 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG419225 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG419226 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG427484 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG427485 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG427486 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG419642 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG419643 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG419644 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG427907 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG427908 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG427909 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG420049 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG420050 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG420051 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG428276 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG428277 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG428278 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG420418 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG420419 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG420420 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG428645 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG428646 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG428647 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG412325 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG412326 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG412327 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG420787 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG420788 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG420789 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG429063 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG429064 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG429065 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG421205 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG421206 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG421207 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG429481 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG429482 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG429483 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG421574 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG421575 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG421576 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG429850 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG429851 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG429852 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG421943 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG421944 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG421945 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG430268 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG430269 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG430270 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG422312 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG422313 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG422314 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG430686 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG430687 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG430688 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG422706 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG422707 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG422708 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG431055 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG431056 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG431057 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG423075 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG423076 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG423077 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG431472 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG431473 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG431474 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_xChartWindow@@3Uqt_meta_stringdata_xChartWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_xChartWindow
	DD	0cH
	DD	00H
	ORG $+4
	DQ	00000000000000a8H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000009dH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000096H
	DD	0ffffffffH
	DD	01aH
	DD	00H
	ORG $+4
	DQ	000000000000007fH
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000082H
	DD	0ffffffffH
	DD	01H
	DD	00H
	ORG $+4
	DQ	000000000000007fH
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	0000000000000069H
	DB	078H
	DB	043H
	DB	068H
	DB	061H
	DB	072H
	DB	074H
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	075H
	DB	070H
	DB	064H
	DB	061H
	DB	074H
	DB	065H
	DB	054H
	DB	061H
	DB	072H
	DB	067H
	DB	065H
	DB	074H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	DB	00H
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	05fH
	DB	070H
	DB	061H
	DB	073H
	DB	073H
	DB	069H
	DB	06eH
	DB	067H
	DB	05fH
	DB	064H
	DB	069H
	DB	073H
	DB	074H
	DB	072H
	DB	069H
	DB	062H
	DB	075H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	050H
	DB	06cH
	DB	06fH
	DB	074H
	DB	046H
	DB	072H
	DB	06fH
	DB	06dH
	DB	043H
	DB	06fH
	DB	06dH
	DB	062H
	DB	06fH
	DB	042H
	DB	06fH
	DB	078H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	DB	069H
	DB	00H
	DB	065H
	DB	064H
	DB	069H
	DB	074H
	DB	069H
	DB	06eH
	DB	067H
	DB	043H
	DB	06fH
	DB	06dH
	DB	06dH
	DB	061H
	DB	06eH
	DB	064H
	DB	00H
	ORG $+8
?qt_meta_data_xChartWindow@@3QBIB DD 08H		; qt_meta_data_xChartWindow
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	03H
	DD	027H
	DD	02H
	DD	0aH
	DD	03H
	DD	00H
	DD	02eH
	DD	02H
	DD	08H
	DD	04H
	DD	01H
	DD	02fH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	032H
	DD	02H
	DD	028H
	DD	06H
	DD	00H
	DD	033H
	DD	02H
	DD	08H
	DD	02bH
	DD	02H
	DD	0aH
	DD	0bH
	DD	02H
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	02H
	DD	05H
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG431889 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+4
$SG431890 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG431891 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG432308 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG432309 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG432310 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG424511 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG424512 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG424513 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG432726 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG432727 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG432728 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG416597 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416598 DB	'asize >= 0 && asize <= aalloc', 00H
	ORG $+2
$SG416606 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416607 DB	'x->ref.isSharable() || options.testFlag(QArrayData::Unsh'
	DB	'arable)', 00H
$SG416608 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416609 DB	'!x->ref.isStatic()', 00H
	ORG $+5
$SG416622 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416623 DB	'int(d->alloc) == aalloc', 00H
$SG416624 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416625 DB	'isDetached()', 00H
	ORG $+3
$SG416626 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416635 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416636 DB	'd->data()', 00H
	ORG $+6
$SG416637 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416638 DB	'uint(d->size) <= d->alloc', 00H
	ORG $+6
$SG416639 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416640 DB	'd != Data::unsharableEmpty()', 00H
	ORG $+3
$SG416641 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416642 DB	'aalloc ? d != Data::sharedNull() : d == Data::sharedNull'
	DB	'()', 00H
	ORG $+5
$SG416643 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416644 DB	'd->alloc >= uint(aalloc)', 00H
	ORG $+7
$SG416645 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qvector.h', 00H
	ORG $+6
$SG416646 DB	'd->size == asize', 00H
	ORG $+7
$SG424946 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+4
$SG424947 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG424948 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG433144 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG433145 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG433146 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG425369 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+4
$SG433562 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+4
$SG425370 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG433563 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG425371 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG433564 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG425792 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG425793 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG425794 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG417643 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG417644 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG417645 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??2@YAPEAX_KPEAX@Z				; operator new
PUBLIC	?_Load_seq_cst_4@std@@YAKPECK@Z			; std::_Load_seq_cst_4
PUBLIC	?_Load_relaxed_4@std@@YAKPECK@Z			; std::_Load_relaxed_4
PUBLIC	?_Load_acquire_4@std@@YAKPECK@Z			; std::_Load_acquire_4
PUBLIC	?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z	; std::_Atomic_load_4
PUBLIC	?_Fetch_add_seq_cst_4@std@@YAKPECKK@Z		; std::_Fetch_add_seq_cst_4
PUBLIC	?_Fetch_add_relaxed_4@std@@YAKPECKK@Z		; std::_Fetch_add_relaxed_4
PUBLIC	?_Fetch_add_acquire_4@std@@YAKPECKK@Z		; std::_Fetch_add_acquire_4
PUBLIC	?_Fetch_add_release_4@std@@YAKPECKK@Z		; std::_Fetch_add_release_4
PUBLIC	?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z ; std::_Atomic_fetch_add_4
PUBLIC	?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z	; std::_Atomic_int::load
PUBLIC	??E_Atomic_int@std@@QEAAHXZ			; std::_Atomic_int::operator++
PUBLIC	?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z ; std::atomic_load_explicit
PUBLIC	?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z ; std::atomic_fetch_add_explicit
PUBLIC	?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z	; std::atomic_fetch_add
PUBLIC	?load@?$QBasicAtomicInteger@H@@QEBAHXZ		; QBasicAtomicInteger<int>::load
PUBLIC	?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ		; QBasicAtomicInteger<int>::ref
PUBLIC	?ref@RefCount@QtPrivate@@QEAA_NXZ		; QtPrivate::RefCount::ref
PUBLIC	??_GQString@@QEAAPEAXI@Z			; QString::`scalar deleting destructor'
PUBLIC	??1?$QListSpecialMethods@VQString@@@@IEAA@XZ	; QListSpecialMethods<QString>::~QListSpecialMethods<QString>
PUBLIC	??0?$QList@VQString@@@@QEAA@AEBV0@@Z		; QList<QString>::QList<QString>
PUBLIC	?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z ; QList<QString>::node_copy
PUBLIC	??0QStringList@@QEAA@AEBV0@@Z			; QStringList::QStringList
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@xChartWindow@@UEBAPEBUQMetaObject@@XZ ; xChartWindow::metaObject
PUBLIC	?qt_metacast@xChartWindow@@UEAAPEAXPEBD@Z	; xChartWindow::qt_metacast
PUBLIC	?qt_metacall@xChartWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xChartWindow::qt_metacall
PUBLIC	?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xChartWindow::qt_static_metacall
PUBLIC	??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z ; QAtomicOps<int>::ref<int>
PUBLIC	??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z ; QAtomicOps<int>::load<int>
PUBLIC	??_C@_02DKCKIIND@?$CFs@				; `string'
PUBLIC	??_C@_0BF@ELBANHFK@Invalid?5memory_order@	; `string'
PUBLIC	??_C@_0GK@HCPCNJPA@c?3?2program?5files?5?$CIx86?$CJ?2microsof@ ; `string'
PUBLIC	??_C@_1NE@JIAMEJOL@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe@ ; `string'
PUBLIC	??_C@_1CO@MPEJOJHF@?$AA?$CC?$AAI?$AAn?$AAv?$AAa?$AAl?$AAi?$AAd?$AA?5?$AAm?$AAe?$AAm?$AAo?$AAr?$AAy@ ; `string'
PUBLIC	??_C@_1CI@NMHCEFB@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAl?$AAo@ ; `string'
PUBLIC	??_C@_1DC@FMPHIJPC@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAf?$AAe@ ; `string'
PUBLIC	?staticMetaObject@xChartWindow@@2UQMetaObject@@B ; xChartWindow::staticMetaObject
EXTRN	??2@YAPEAX_K@Z:PROC				; operator new
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	__imp__invalid_parameter:PROC
EXTRN	__imp__CrtDbgReport:PROC
EXTRN	memcpy:PROC
EXTRN	strcmp:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_??1QString@@QEAA@XZ:PROC
EXTRN	__imp_?detach@QListData@@QEAAPEAUData@1@H@Z:PROC
EXTRN	__imp_?dispose@QListData@@SAXPEAUData@1@@Z:PROC
EXTRN	__imp_?begin@QListData@@QEBAPEAPEAXXZ:PROC
EXTRN	__imp_?end@QListData@@QEBAPEAPEAXXZ:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?updateTargetItem@xChartWindow@@QEAAXHVQString@@VQStringList@@@Z:PROC ; xChartWindow::updateTargetItem
EXTRN	?click_passing_distribution@xChartWindow@@AEAAXXZ:PROC ; xChartWindow::click_passing_distribution
EXTRN	?PlotFromComboBoxItem@xChartWindow@@AEAAXH@Z:PROC ; xChartWindow::PlotFromComboBoxItem
EXTRN	?editingCommand@xChartWindow@@AEAAXXZ:PROC	; xChartWindow::editingCommand
EXTRN	_CxxThrowException:PROC
EXTRN	__CxxFrameHandler3:PROC
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@xChartWindow@@2UQMetaObject@@B DB 030H DUP (?) ; xChartWindow::staticMetaObject
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Load_seq_cst_4@std@@YAKPECK@Z DD imagerel $LN3
	DD	imagerel $LN3+27
	DD	imagerel $unwind$?_Load_seq_cst_4@std@@YAKPECK@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Load_relaxed_4@std@@YAKPECK@Z DD imagerel $LN3
	DD	imagerel $LN3+27
	DD	imagerel $unwind$?_Load_relaxed_4@std@@YAKPECK@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Load_acquire_4@std@@YAKPECK@Z DD imagerel $LN3
	DD	imagerel $LN3+24
	DD	imagerel $unwind$?_Load_acquire_4@std@@YAKPECK@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z DD imagerel $LN13
	DD	imagerel $LN13+204
	DD	imagerel $unwind$?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z DD imagerel $LN15
	DD	imagerel $LN15+268
	DD	imagerel $unwind$?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z DD imagerel $LN3
	DD	imagerel $LN3+32
	DD	imagerel $unwind$?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??E_Atomic_int@std@@QEAAHXZ DD imagerel $LN3
	DD	imagerel $LN3+31
	DD	imagerel $unwind$??E_Atomic_int@std@@QEAAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z DD imagerel $LN3
	DD	imagerel $LN3+45
	DD	imagerel $unwind$?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z DD imagerel $LN3
	DD	imagerel $LN3+55
	DD	imagerel $unwind$?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?load@?$QBasicAtomicInteger@H@@QEBAHXZ DD imagerel $LN3
	DD	imagerel $LN3+27
	DD	imagerel $unwind$?load@?$QBasicAtomicInteger@H@@QEBAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?ref@RefCount@QtPrivate@@QEAA_NXZ DD imagerel $LN5
	DD	imagerel $LN5+64
	DD	imagerel $unwind$?ref@RefCount@QtPrivate@@QEAA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GQString@@QEAAPEAXI@Z DD imagerel $LN4
	DD	imagerel $LN4+60
	DD	imagerel $unwind$??_GQString@@QEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$QList@VQString@@@@QEAA@AEBV0@@Z DD imagerel $LN12
	DD	imagerel $LN12+173
	DD	imagerel $unwind$??0?$QList@VQString@@@@QEAA@AEBV0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA DD imagerel ?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA
	DD	imagerel ?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA+24
	DD	imagerel $unwind$?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA DD imagerel ?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA
	DD	imagerel ?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA+50
	DD	imagerel $unwind$?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD imagerel $LN33
	DD	imagerel $LN33+419
	DD	imagerel $unwind$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA DD imagerel ?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA
	DD	imagerel ?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA+134
	DD	imagerel $unwind$?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA DD imagerel ?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA
	DD	imagerel ?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA+91
	DD	imagerel $unwind$?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0QStringList@@QEAA@AEBV0@@Z DD imagerel $LN4
	DD	imagerel $LN4+39
	DD	imagerel $unwind$??0QStringList@@QEAA@AEBV0@@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?metaObject@xChartWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@xChartWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@xChartWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@xChartWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@xChartWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@xChartWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN14
	DD	imagerel $LN14+325
	DD	imagerel $unwind$?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z DD imagerel $LN5
	DD	imagerel $LN5+51
	DD	imagerel $unwind$??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z DD imagerel $LN3
	DD	imagerel $LN3+26
	DD	imagerel $unwind$??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xChartWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xChartWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xChartWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT ??_C@_1DC@FMPHIJPC@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAf?$AAe@
CONST	SEGMENT
??_C@_1DC@FMPHIJPC@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAf?$AAe@ DB 's'
	DB	00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H, 'A', 00H
	DB	't', 00H, 'o', 00H, 'm', 00H, 'i', 00H, 'c', 00H, '_', 00H, 'f'
	DB	00H, 'e', 00H, 't', 00H, 'c', 00H, 'h', 00H, '_', 00H, 'a', 00H
	DB	'd', 00H, 'd', 00H, '_', 00H, '4', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1CI@NMHCEFB@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAl?$AAo@
CONST	SEGMENT
??_C@_1CI@NMHCEFB@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAl?$AAo@ DB 's'
	DB	00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H, 'A', 00H
	DB	't', 00H, 'o', 00H, 'm', 00H, 'i', 00H, 'c', 00H, '_', 00H, 'l'
	DB	00H, 'o', 00H, 'a', 00H, 'd', 00H, '_', 00H, '4', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1CO@MPEJOJHF@?$AA?$CC?$AAI?$AAn?$AAv?$AAa?$AAl?$AAi?$AAd?$AA?5?$AAm?$AAe?$AAm?$AAo?$AAr?$AAy@
CONST	SEGMENT
??_C@_1CO@MPEJOJHF@?$AA?$CC?$AAI?$AAn?$AAv?$AAa?$AAl?$AAi?$AAd?$AA?5?$AAm?$AAe?$AAm?$AAo?$AAr?$AAy@ DB '"'
	DB	00H, 'I', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H, 'i', 00H
	DB	'd', 00H, ' ', 00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r'
	DB	00H, 'y', 00H, '_', 00H, 'o', 00H, 'r', 00H, 'd', 00H, 'e', 00H
	DB	'r', 00H, '"', 00H, 00H, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_1NE@JIAMEJOL@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe@
CONST	SEGMENT
??_C@_1NE@JIAMEJOL@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe@ DB 'c'
	DB	00H, ':', 00H, '\', 00H, 'p', 00H, 'r', 00H, 'o', 00H, 'g', 00H
	DB	'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'f', 00H, 'i', 00H, 'l'
	DB	00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H, '8', 00H
	DB	'6', 00H, ')', 00H, '\', 00H, 'm', 00H, 'i', 00H, 'c', 00H, 'r'
	DB	00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H, ' ', 00H
	DB	'v', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l', 00H, ' '
	DB	00H, 's', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H, 'o', 00H
	DB	'\', 00H, '2', 00H, '0', 00H, '1', 00H, '7', 00H, '\', 00H, 'c'
	DB	00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H, 'i', 00H
	DB	't', 00H, 'y', 00H, '\', 00H, 'v', 00H, 'c', 00H, '\', 00H, 't'
	DB	00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H, 'm', 00H
	DB	's', 00H, 'v', 00H, 'c', 00H, '\', 00H, '1', 00H, '4', 00H, '.'
	DB	00H, '1', 00H, '6', 00H, '.', 00H, '2', 00H, '7', 00H, '0', 00H
	DB	'2', 00H, '3', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c', 00H, 'l'
	DB	00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H, 'a', 00H
	DB	't', 00H, 'o', 00H, 'm', 00H, 'i', 00H, 'c', 00H, '.', 00H, 'h'
	DB	00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0GK@HCPCNJPA@c?3?2program?5files?5?$CIx86?$CJ?2microsof@
CONST	SEGMENT
??_C@_0GK@HCPCNJPA@c?3?2program?5files?5?$CIx86?$CJ?2microsof@ DB 'c:\pro'
	DB	'gram files (x86)\microsoft visual studio\2017\community\vc\to'
	DB	'ols\msvc\14.16.27023\include\xatomic.h', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@ELBANHFK@Invalid?5memory_order@
CONST	SEGMENT
??_C@_0BF@ELBANHFK@Invalid?5memory_order@ DB 'Invalid memory_order', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_02DKCKIIND@?$CFs@
CONST	SEGMENT
??_C@_02DKCKIIND@?$CFs@ DB '%s', 00H			; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z DD 010901H
	DD	06209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@xChartWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@xChartWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@xChartWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0c217H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0QStringList@@QEAA@AEBV0@@Z DD 010e01H
	DD	0420eH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA DD 020a19H
	DD	05006320aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA DD 020a19H
	DD	05006320aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD imagerel ?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
	DD	0ffffffffH
	DD	imagerel ?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z+62
	DD	00H
	DD	imagerel ?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z+200
	DD	0ffffffffH
	DD	imagerel ?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z+214
	DD	02H
	DD	imagerel ?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z+304
	DD	0ffffffffH
	DD	imagerel ?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA
	DD	00H
	DD	imagerel ?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA+13
	DD	01H
	DD	imagerel ?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA+120
	DD	00H
	DD	imagerel ?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA+13
	DD	03H
	DD	imagerel ?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA+77
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$handlerMap$1$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD 040H
	DD	00H
	DD	00H
	DD	imagerel ?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA
	DD	038H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$handlerMap$0$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD 040H
	DD	00H
	DD	00H
	DD	imagerel ?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA
	DD	038H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$tryMap$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD 00H
	DD	00H
	DD	01H
	DD	01H
	DD	imagerel $handlerMap$0$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
	DD	02H
	DD	02H
	DD	03H
	DD	01H
	DD	imagerel $handlerMap$1$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD 0ffffffffH
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	0ffffffffH
	DD	00H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD 019930522H
	DD	04H
	DD	imagerel $stateUnwindMap$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
	DD	02H
	DD	imagerel $tryMap$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
	DD	0aH
	DD	imagerel $ip2state$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
	DD	080H
	DD	00H
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z DD 022719H
	DD	013011bH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA DD 020a19H
	DD	05006320aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??0?$QList@VQString@@@@QEAA@AEBV0@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA DD 020601H
	DD	050023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0?$QList@VQString@@@@QEAA@AEBV0@@Z DD imagerel ??0?$QList@VQString@@@@QEAA@AEBV0@@Z
	DD	0ffffffffH
	DD	imagerel ??0?$QList@VQString@@@@QEAA@AEBV0@@Z+23
	DD	00H
	DD	imagerel ??0?$QList@VQString@@@@QEAA@AEBV0@@Z+85
	DD	01H
	DD	imagerel ??0?$QList@VQString@@@@QEAA@AEBV0@@Z+161
	DD	00H
	DD	imagerel ??0?$QList@VQString@@@@QEAA@AEBV0@@Z+163
	DD	0ffffffffH
	DD	imagerel ?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA
	DD	00H
	DD	imagerel ?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA+13
	DD	02H
	DD	imagerel ?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA+36
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$handlerMap$0$??0?$QList@VQString@@@@QEAA@AEBV0@@Z DD 040H
	DD	00H
	DD	00H
	DD	imagerel ?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA
	DD	038H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$tryMap$??0?$QList@VQString@@@@QEAA@AEBV0@@Z DD 01H
	DD	01H
	DD	02H
	DD	01H
	DD	imagerel $handlerMap$0$??0?$QList@VQString@@@@QEAA@AEBV0@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0?$QList@VQString@@@@QEAA@AEBV0@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA
	DD	00H
	DD	00H
	DD	00H
	DD	00H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??0?$QList@VQString@@@@QEAA@AEBV0@@Z DD 019930522H
	DD	03H
	DD	imagerel $stateUnwindMap$??0?$QList@VQString@@@@QEAA@AEBV0@@Z
	DD	01H
	DD	imagerel $tryMap$??0?$QList@VQString@@@@QEAA@AEBV0@@Z
	DD	08H
	DD	imagerel $ip2state$??0?$QList@VQString@@@@QEAA@AEBV0@@Z
	DD	030H
	DD	00H
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$QList@VQString@@@@QEAA@AEBV0@@Z DD 011719H
	DD	0820eH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??0?$QList@VQString@@@@QEAA@AEBV0@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GQString@@QEAAPEAXI@Z DD 010d01H
	DD	0420dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ref@RefCount@QtPrivate@@QEAA_NXZ DD 010901H
	DD	06209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ DD imagerel ?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ
	DD	0ffffffffH
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ DD 019930522H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	imagerel $ip2state$?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ
	DD	020H
	DD	00H
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ DD 011219H
	DD	06209H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?load@?$QBasicAtomicInteger@H@@QEBAHXZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z DD 010d01H
	DD	0420dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z DD imagerel ?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z
	DD	0ffffffffH
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z DD 019930522H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	imagerel $ip2state$?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z
	DD	020H
	DD	00H
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z DD 011b19H
	DD	06212H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z DD imagerel ?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z
	DD	0ffffffffH
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z DD 019930522H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	imagerel $ip2state$?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z
	DD	020H
	DD	00H
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z DD 011619H
	DD	0620dH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??E_Atomic_int@std@@QEAAHXZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z DD 010d01H
	DD	0420dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z DD 011201H
	DD	08212H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z DD 010d01H
	DD	0820dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Load_acquire_4@std@@YAKPECK@Z DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Load_relaxed_4@std@@YAKPECK@Z DD 010901H
	DD	02209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Load_seq_cst_4@std@@YAKPECK@Z DD 010901H
	DD	02209H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z
_TEXT	SEGMENT
_q_value$ = 48
??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z PROC ; QAtomicOps<int>::load<int>, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qatomic_cxx11.h
; Line 226
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 227
	xor	edx, edx
	mov	rcx, QWORD PTR _q_value$[rsp]
	call	?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z ; std::_Atomic_int::load
; Line 228
	add	rsp, 40					; 00000028H
	ret	0
??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z ENDP ; QAtomicOps<int>::load<int>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z
_TEXT	SEGMENT
tv71 = 32
_q_value$ = 64
??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z PROC ; QAtomicOps<int>::ref<int>, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qatomic_cxx11.h
; Line 264
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 265
	mov	rcx, QWORD PTR _q_value$[rsp]
	call	??E_Atomic_int@std@@QEAAHXZ		; std::_Atomic_int::operator++
	test	eax, eax
	je	SHORT $LN3@ref
	mov	DWORD PTR tv71[rsp], 1
	jmp	SHORT $LN4@ref
$LN3@ref:
	mov	DWORD PTR tv71[rsp], 0
$LN4@ref:
	movzx	eax, BYTE PTR tv71[rsp]
; Line 266
	add	rsp, 56					; 00000038H
	ret	0
??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z ENDP ; QAtomicOps<int>::ref<int>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@xChartWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xChartWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xChartWindow::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xchartwindow.cpp
; Line 96
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xChartWindow@@2UQMetaObject@@B, rax
; Line 97
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_xChartWindow@@3Uqt_meta_stringdata_xChartWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@xChartWindow@@2UQMetaObject@@B+8, rax
; Line 98
	lea	rax, OFFSET FLAT:?qt_meta_data_xChartWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@xChartWindow@@2UQMetaObject@@B+16, rax
; Line 99
	lea	rax, OFFSET FLAT:?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xChartWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@xChartWindow@@2UQMetaObject@@B+24, rax
; Line 100
	mov	QWORD PTR ?staticMetaObject@xChartWindow@@2UQMetaObject@@B+32, 0
; Line 101
	mov	QWORD PTR ?staticMetaObject@xChartWindow@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@xChartWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xChartWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
$T2 = 48
$T3 = 56
tv143 = 64
tv145 = 72
$T4 = 80
$T5 = 88
_o$ = 112
_c$ = 120
_id$ = 128
_a$ = 136
?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xChartWindow::qt_static_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xchartwindow.cpp
; Line 80
$LN14:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H
; Line 81
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 82
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 84
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	$LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	$LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	$LN8@qt_static_
	cmp	DWORD PTR tv69[rsp], 4
	je	$LN9@qt_static_
	jmp	$LN4@qt_static_
$LN5@qt_static_:
; Line 85
	lea	rax, QWORD PTR $T4[rsp]
	mov	QWORD PTR $T2[rsp], rax
	lea	rax, QWORD PTR $T5[rsp]
	mov	QWORD PTR $T3[rsp], rax
	mov	eax, 8
	imul	rax, rax, 3
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T2[rsp]
	call	??0QStringList@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv143[rsp], rax
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv145[rsp], rax
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	r9, QWORD PTR tv143[rsp]
	mov	r8, QWORD PTR tv145[rsp]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?updateTargetItem@xChartWindow@@QEAAXHVQString@@VQStringList@@@Z ; xChartWindow::updateTargetItem
	jmp	SHORT $LN4@qt_static_
$LN6@qt_static_:
; Line 86
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?click_passing_distribution@xChartWindow@@AEAAXXZ ; xChartWindow::click_passing_distribution
	jmp	SHORT $LN4@qt_static_
$LN7@qt_static_:
; Line 87
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?PlotFromComboBoxItem@xChartWindow@@AEAAXH@Z ; xChartWindow::PlotFromComboBoxItem
	jmp	SHORT $LN4@qt_static_
$LN8@qt_static_:
; Line 88
	xor	edx, edx
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?PlotFromComboBoxItem@xChartWindow@@AEAAXH@Z ; xChartWindow::PlotFromComboBoxItem
	jmp	SHORT $LN4@qt_static_
$LN9@qt_static_:
; Line 89
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?editingCommand@xChartWindow@@AEAAXXZ	; xChartWindow::editingCommand
$LN4@qt_static_:
; Line 93
	add	rsp, 104				; 00000068H
	ret	0
?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xChartWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xChartWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xChartWindow::qt_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xchartwindow.cpp
; Line 119
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 120
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 121
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 123
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 124
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN5@qt_metacal
; Line 125
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@xChartWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xChartWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 126
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 127
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 128
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN7@qt_metacal
; Line 129
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 130
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 132
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 133
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@xChartWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xChartWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@xChartWindow@@UEAAPEAXPEBD@Z PROC		; xChartWindow::qt_metacast
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xchartwindow.cpp
; Line 111
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 112
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 113
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_xChartWindow@@3Uqt_meta_stringdata_xChartWindow_t@@B+168
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 114
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 115
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 116
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@xChartWindow@@UEAAPEAXPEBD@Z ENDP		; xChartWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@xChartWindow@@UEBAPEBUQMetaObject@@XZ PROC	; xChartWindow::metaObject
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xchartwindow.cpp
; Line 106
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 107
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xChartWindow@@2UQMetaObject@@B ; xChartWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 108
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@xChartWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; xChartWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0QStringList@@QEAA@AEBV0@@Z
_TEXT	SEGMENT
this$ = 48
__that$ = 56
??0QStringList@@QEAA@AEBV0@@Z PROC			; QStringList::QStringList, COMDAT
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rdx, QWORD PTR __that$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	??0?$QList@VQString@@@@QEAA@AEBV0@@Z	; QList<QString>::QList<QString>
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??0QStringList@@QEAA@AEBV0@@Z ENDP			; QStringList::QStringList
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z
_TEXT	SEGMENT
current$ = 32
$T1 = 40
tv77 = 48
$T2 = 56
tv156 = 64
tv83 = 72
tv82 = 80
$T3 = 88
tv89 = 96
$T4 = 104
tv139 = 112
tv138 = 120
$T5 = 128
this$ = 160
from$ = 168
to$ = 176
src$ = 184
?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z PROC ; QList<QString>::node_copy, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qlist.h
; Line 460
$LN33:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 152				; 00000098H
	mov	QWORD PTR $T5[rsp], -2
; Line 461
	mov	rax, QWORD PTR from$[rsp]
	mov	QWORD PTR current$[rsp], rax
; Line 462
	xor	eax, eax
	test	eax, eax
	je	$LN10@node_copy
$LN2@node_copy:
; Line 464
	mov	rax, QWORD PTR to$[rsp]
	cmp	QWORD PTR current$[rsp], rax
	je	SHORT $LN3@node_copy
; Line 465
	mov	ecx, 8
	call	??2@YAPEAX_K@Z				; operator new
	mov	QWORD PTR tv156[rsp], rax
	mov	rax, QWORD PTR tv156[rsp]
	mov	QWORD PTR $T1[rsp], rax
	cmp	QWORD PTR $T1[rsp], 0
	je	SHORT $LN18@node_copy
	mov	rax, QWORD PTR src$[rsp]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR $T1[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv77[rsp], rax
	jmp	SHORT $LN19@node_copy
$LN18@node_copy:
	mov	QWORD PTR tv77[rsp], 0
$LN19@node_copy:
	mov	rax, QWORD PTR current$[rsp]
	mov	rcx, QWORD PTR tv77[rsp]
	mov	QWORD PTR [rax], rcx
; Line 466
	mov	rax, QWORD PTR current$[rsp]
	add	rax, 8
	mov	QWORD PTR current$[rsp], rax
; Line 467
	mov	rax, QWORD PTR src$[rsp]
	add	rax, 8
	mov	QWORD PTR src$[rsp], rax
; Line 468
	jmp	$LN2@node_copy
$LN3@node_copy:
	jmp	SHORT $LN26@node_copy
$LN27@node_copy:
$LN26@node_copy:
; Line 475
	jmp	$LN17@node_copy
$LN10@node_copy:
	xor	eax, eax
	cmp	eax, 1
	je	SHORT $LN13@node_copy
$LN6@node_copy:
; Line 477
	mov	rax, QWORD PTR to$[rsp]
	cmp	QWORD PTR current$[rsp], rax
	je	SHORT $LN7@node_copy
; Line 478
	mov	rdx, QWORD PTR current$[rsp]
	mov	ecx, 8
	call	??2@YAPEAX_KPEAX@Z			; operator new
	mov	QWORD PTR $T4[rsp], rax
	mov	rdx, QWORD PTR src$[rsp]
	mov	rcx, QWORD PTR $T4[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
; Line 479
	mov	rax, QWORD PTR current$[rsp]
	add	rax, 8
	mov	QWORD PTR current$[rsp], rax
; Line 480
	mov	rax, QWORD PTR src$[rsp]
	add	rax, 8
	mov	QWORD PTR src$[rsp], rax
; Line 481
	jmp	SHORT $LN6@node_copy
$LN7@node_copy:
	jmp	SHORT $LN28@node_copy
$LN29@node_copy:
$LN28@node_copy:
; Line 487
	jmp	SHORT $LN17@node_copy
$LN13@node_copy:
; Line 488
	mov	rax, QWORD PTR from$[rsp]
	cmp	QWORD PTR src$[rsp], rax
	je	SHORT $LN17@node_copy
	mov	rax, QWORD PTR from$[rsp]
	mov	rcx, QWORD PTR to$[rsp]
	sub	rcx, rax
	mov	rax, rcx
	sar	rax, 3
	test	rax, rax
	jle	SHORT $LN17@node_copy
; Line 489
	mov	rax, QWORD PTR from$[rsp]
	mov	rcx, QWORD PTR to$[rsp]
	sub	rcx, rax
	mov	rax, rcx
	sar	rax, 3
	shl	rax, 3
	mov	r8, rax
	mov	rdx, QWORD PTR src$[rsp]
	mov	rcx, QWORD PTR from$[rsp]
	call	memcpy
$LN17@node_copy:
; Line 491
	add	rsp, 152				; 00000098H
	ret	0
$LN30@node_copy:
?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z ENDP ; QList<QString>::node_copy
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
current$ = 32
$T1 = 40
tv77 = 48
$T2 = 56
tv156 = 64
tv83 = 72
tv82 = 80
$T3 = 88
tv89 = 96
$T4 = 104
tv139 = 112
tv138 = 120
$T5 = 128
this$ = 160
from$ = 168
to$ = 176
src$ = 184
?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA PROC ; `QList<QString>::node_copy'::`1'::catch$0
; Line 469
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
__catch$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z$0:
$LN4@catch$0:
; Line 470
	mov	rax, QWORD PTR current$[rbp]
	mov	QWORD PTR tv82[rbp], rax
	mov	rax, QWORD PTR from$[rbp]
	mov	QWORD PTR tv83[rbp], rax
	mov	rax, QWORD PTR current$[rbp]
	sub	rax, 8
	mov	QWORD PTR current$[rbp], rax
	mov	rax, QWORD PTR tv83[rbp]
	cmp	QWORD PTR tv82[rbp], rax
	je	SHORT $LN5@catch$0
; Line 471
	mov	rax, QWORD PTR current$[rbp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR $T3[rbp], rax
	mov	rax, QWORD PTR $T3[rbp]
	mov	QWORD PTR $T2[rbp], rax
	cmp	QWORD PTR $T2[rbp], 0
	je	SHORT $LN20@catch$0
	mov	edx, 1
	mov	rcx, QWORD PTR $T2[rbp]
	call	??_GQString@@QEAAPEAXI@Z
	mov	QWORD PTR tv89[rbp], rax
	jmp	SHORT $LN21@catch$0
$LN20@catch$0:
	mov	QWORD PTR tv89[rbp], 0
$LN21@catch$0:
	jmp	SHORT $LN4@catch$0
$LN5@catch$0:
; Line 472
	xor	edx, edx
	xor	ecx, ecx
	call	_CxxThrowException
	npad	1
; Line 473
	lea	rax, $LN27@catch$0
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA ENDP ; `QList<QString>::node_copy'::`1'::catch$0
current$ = 32
$T1 = 40
tv77 = 48
$T2 = 56
tv156 = 64
tv83 = 72
tv82 = 80
$T3 = 88
tv89 = 96
$T4 = 104
tv139 = 112
tv138 = 120
$T5 = 128
this$ = 160
from$ = 168
to$ = 176
src$ = 184
?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA PROC ; `QList<QString>::node_copy'::`1'::catch$1
; Line 482
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
__catch$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z$2:
$LN8@catch$1:
; Line 483
	mov	rax, QWORD PTR current$[rbp]
	mov	QWORD PTR tv138[rbp], rax
	mov	rax, QWORD PTR from$[rbp]
	mov	QWORD PTR tv139[rbp], rax
	mov	rax, QWORD PTR current$[rbp]
	sub	rax, 8
	mov	QWORD PTR current$[rbp], rax
	mov	rax, QWORD PTR tv139[rbp]
	cmp	QWORD PTR tv138[rbp], rax
	je	SHORT $LN9@catch$1
; Line 484
	xor	edx, edx
	mov	rcx, QWORD PTR current$[rbp]
	call	??_GQString@@QEAAPEAXI@Z
	jmp	SHORT $LN8@catch$1
$LN9@catch$1:
; Line 485
	xor	edx, edx
	xor	ecx, ecx
	call	_CxxThrowException
	npad	1
; Line 486
	lea	rax, $LN29@catch$1
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA ENDP ; `QList<QString>::node_copy'::`1'::catch$1
text$x	ENDS
; Function compile flags: /Odtp
;	COMDAT text$x
text$x	SEGMENT
current$ = 32
$T1 = 40
tv77 = 48
$T2 = 56
tv156 = 64
tv83 = 72
tv82 = 80
$T3 = 88
tv89 = 96
$T4 = 104
tv139 = 112
tv138 = 120
$T5 = 128
this$ = 160
from$ = 168
to$ = 176
src$ = 184
?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA PROC ; `QList<QString>::node_copy'::`1'::catch$0
; Line 469
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
__catch$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z$0:
$LN4@catch$0:
; Line 470
	mov	rax, QWORD PTR current$[rbp]
	mov	QWORD PTR tv82[rbp], rax
	mov	rax, QWORD PTR from$[rbp]
	mov	QWORD PTR tv83[rbp], rax
	mov	rax, QWORD PTR current$[rbp]
	sub	rax, 8
	mov	QWORD PTR current$[rbp], rax
	mov	rax, QWORD PTR tv83[rbp]
	cmp	QWORD PTR tv82[rbp], rax
	je	SHORT $LN5@catch$0
; Line 471
	mov	rax, QWORD PTR current$[rbp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR $T3[rbp], rax
	mov	rax, QWORD PTR $T3[rbp]
	mov	QWORD PTR $T2[rbp], rax
	cmp	QWORD PTR $T2[rbp], 0
	je	SHORT $LN20@catch$0
	mov	edx, 1
	mov	rcx, QWORD PTR $T2[rbp]
	call	??_GQString@@QEAAPEAXI@Z
	mov	QWORD PTR tv89[rbp], rax
	jmp	SHORT $LN21@catch$0
$LN20@catch$0:
	mov	QWORD PTR tv89[rbp], 0
$LN21@catch$0:
	jmp	SHORT $LN4@catch$0
$LN5@catch$0:
; Line 472
	xor	edx, edx
	xor	ecx, ecx
	call	_CxxThrowException
	npad	1
; Line 473
	lea	rax, $LN27@catch$0
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
?catch$0@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA ENDP ; `QList<QString>::node_copy'::`1'::catch$0
text$x	ENDS
; Function compile flags: /Odtp
;	COMDAT text$x
text$x	SEGMENT
current$ = 32
$T1 = 40
tv77 = 48
$T2 = 56
tv156 = 64
tv83 = 72
tv82 = 80
$T3 = 88
tv89 = 96
$T4 = 104
tv139 = 112
tv138 = 120
$T5 = 128
this$ = 160
from$ = 168
to$ = 176
src$ = 184
?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA PROC ; `QList<QString>::node_copy'::`1'::catch$1
; Line 482
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
__catch$?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z$2:
$LN8@catch$1:
; Line 483
	mov	rax, QWORD PTR current$[rbp]
	mov	QWORD PTR tv138[rbp], rax
	mov	rax, QWORD PTR from$[rbp]
	mov	QWORD PTR tv139[rbp], rax
	mov	rax, QWORD PTR current$[rbp]
	sub	rax, 8
	mov	QWORD PTR current$[rbp], rax
	mov	rax, QWORD PTR tv139[rbp]
	cmp	QWORD PTR tv138[rbp], rax
	je	SHORT $LN9@catch$1
; Line 484
	xor	edx, edx
	mov	rcx, QWORD PTR current$[rbp]
	call	??_GQString@@QEAAPEAXI@Z
	jmp	SHORT $LN8@catch$1
$LN9@catch$1:
; Line 485
	xor	edx, edx
	xor	ecx, ecx
	call	_CxxThrowException
	npad	1
; Line 486
	lea	rax, $LN29@catch$1
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
?catch$1@?0??node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z@4HA ENDP ; `QList<QString>::node_copy'::`1'::catch$1
text$x	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0?$QList@VQString@@@@QEAA@AEBV0@@Z
_TEXT	SEGMENT
tv93 = 32
tv129 = 40
$T1 = 48
this$ = 80
l$ = 88
??0?$QList@VQString@@@@QEAA@AEBV0@@Z PROC		; QList<QString>::QList<QString>, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qlist.h
; Line 811
$LN12:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
	mov	QWORD PTR $T1[rsp], -2
; Line 810
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR l$[rsp]
	mov	rcx, QWORD PTR [rcx]
	mov	QWORD PTR [rax], rcx
; Line 812
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rcx, rax
	call	?ref@RefCount@QtPrivate@@QEAA_NXZ	; QtPrivate::RefCount::ref
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN2@QList
; Line 813
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rcx, QWORD PTR this$[rsp]
	mov	edx, DWORD PTR [rax+4]
	call	QWORD PTR __imp_?detach@QListData@@QEAAPEAUData@1@H@Z
	npad	1
; Line 816
	mov	rax, QWORD PTR l$[rsp]
	mov	rcx, rax
	call	QWORD PTR __imp_?begin@QListData@@QEBAPEAPEAXXZ
	mov	QWORD PTR tv93[rsp], rax
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?end@QListData@@QEBAPEAPEAXXZ
	mov	QWORD PTR tv129[rsp], rax
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?begin@QListData@@QEBAPEAPEAXXZ
	mov	rcx, QWORD PTR tv93[rsp]
	mov	r9, rcx
	mov	rcx, QWORD PTR tv129[rsp]
	mov	r8, rcx
	mov	rdx, rax
	mov	rcx, QWORD PTR this$[rsp]
	call	?node_copy@?$QList@VQString@@@@AEAAXPEAUNode@1@00@Z ; QList<QString>::node_copy
	npad	1
	jmp	SHORT $LN2@QList
$LN9@QList:
$LN2@QList:
; Line 824
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 72					; 00000048H
	ret	0
$LN10@QList:
??0?$QList@VQString@@@@QEAA@AEBV0@@Z ENDP		; QList<QString>::QList<QString>
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
tv93 = 32
tv129 = 40
$T1 = 48
this$ = 80
l$ = 88
?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA PROC ; `QList<QString>::QList<QString>'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR this$[rbp]
	call	??1?$QListSpecialMethods@VQString@@@@IEAA@XZ ; QListSpecialMethods<QString>::~QListSpecialMethods<QString>
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA ENDP ; `QList<QString>::QList<QString>'::`1'::dtor$0
text$x	ENDS
;	COMDAT text$x
text$x	SEGMENT
tv93 = 32
tv129 = 40
$T1 = 48
this$ = 80
l$ = 88
?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA PROC ; `QList<QString>::QList<QString>'::`1'::catch$1
; Line 819
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
__catch$??0?$QList@VQString@@@@QEAA@AEBV0@@Z$0:
; Line 820
	mov	rax, QWORD PTR this$[rbp]
	mov	rcx, QWORD PTR [rax]
	call	QWORD PTR __imp_?dispose@QListData@@SAXPEAUData@1@@Z
; Line 821
	xor	edx, edx
	xor	ecx, ecx
	call	_CxxThrowException
	npad	1
; Line 822
	lea	rax, $LN9@catch$1
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA ENDP ; `QList<QString>::QList<QString>'::`1'::catch$1
text$x	ENDS
; Function compile flags: /Odtp
;	COMDAT text$x
text$x	SEGMENT
tv93 = 32
tv129 = 40
$T1 = 48
this$ = 80
l$ = 88
?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA PROC ; `QList<QString>::QList<QString>'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR this$[rbp]
	call	??1?$QListSpecialMethods@VQString@@@@IEAA@XZ ; QListSpecialMethods<QString>::~QListSpecialMethods<QString>
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA ENDP ; `QList<QString>::QList<QString>'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
;	COMDAT text$x
text$x	SEGMENT
tv93 = 32
tv129 = 40
$T1 = 48
this$ = 80
l$ = 88
?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA PROC ; `QList<QString>::QList<QString>'::`1'::catch$1
; Line 819
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
__catch$??0?$QList@VQString@@@@QEAA@AEBV0@@Z$0:
; Line 820
	mov	rax, QWORD PTR this$[rbp]
	mov	rcx, QWORD PTR [rax]
	call	QWORD PTR __imp_?dispose@QListData@@SAXPEAUData@1@@Z
; Line 821
	xor	edx, edx
	xor	ecx, ecx
	call	_CxxThrowException
	npad	1
; Line 822
	lea	rax, $LN9@catch$1
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
?catch$1@?0???0?$QList@VQString@@@@QEAA@AEBV0@@Z@4HA ENDP ; `QList<QString>::QList<QString>'::`1'::catch$1
text$x	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1?$QListSpecialMethods@VQString@@@@IEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1?$QListSpecialMethods@VQString@@@@IEAA@XZ PROC	; QListSpecialMethods<QString>::~QListSpecialMethods<QString>, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qstringlist.h
; Line 69
	mov	QWORD PTR [rsp+8], rcx
	ret	0
??1?$QListSpecialMethods@VQString@@@@IEAA@XZ ENDP	; QListSpecialMethods<QString>::~QListSpecialMethods<QString>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??_GQString@@QEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_GQString@@QEAAPEAXI@Z PROC				; QString::`scalar deleting destructor', COMDAT
$LN4:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	mov	eax, DWORD PTR __flags$[rsp]
	and	eax, 1
	test	eax, eax
	je	SHORT $LN2@scalar
	mov	edx, 8
	mov	rcx, QWORD PTR this$[rsp]
	call	??3@YAXPEAX_K@Z				; operator delete
$LN2@scalar:
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??_GQString@@QEAAPEAXI@Z ENDP				; QString::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?ref@RefCount@QtPrivate@@QEAA_NXZ
_TEXT	SEGMENT
count$ = 32
this$ = 64
?ref@RefCount@QtPrivate@@QEAA_NXZ PROC			; QtPrivate::RefCount::ref, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qrefcount.h
; Line 54
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 55
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, rax
	call	?load@?$QBasicAtomicInteger@H@@QEBAHXZ	; QBasicAtomicInteger<int>::load
	mov	DWORD PTR count$[rsp], eax
; Line 57
	cmp	DWORD PTR count$[rsp], 0
	jne	SHORT $LN2@ref
; Line 58
	xor	al, al
	jmp	SHORT $LN1@ref
$LN2@ref:
; Line 60
	cmp	DWORD PTR count$[rsp], -1
	je	SHORT $LN3@ref
; Line 61
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, rax
	call	?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ	; QBasicAtomicInteger<int>::ref
$LN3@ref:
; Line 62
	mov	al, 1
$LN1@ref:
; Line 63
	add	rsp, 56					; 00000038H
	ret	0
?ref@RefCount@QtPrivate@@QEAA_NXZ ENDP			; QtPrivate::RefCount::ref
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 64
?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ PROC		; QBasicAtomicInteger<int>::ref, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qbasicatomic.h
; Line 114
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
	mov	QWORD PTR $T1[rsp], -2
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, rax
	call	??$ref@H@?$QAtomicOps@H@@SA_NAEAU?$atomic@H@std@@@Z ; QAtomicOps<int>::ref<int>
	npad	1
	add	rsp, 56					; 00000038H
	ret	0
?ref@?$QBasicAtomicInteger@H@@QEAA_NXZ ENDP		; QBasicAtomicInteger<int>::ref
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?load@?$QBasicAtomicInteger@H@@QEBAHXZ
_TEXT	SEGMENT
this$ = 48
?load@?$QBasicAtomicInteger@H@@QEBAHXZ PROC		; QBasicAtomicInteger<int>::load, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qbasicatomic.h
; Line 103
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, rax
	call	??$load@H@?$QAtomicOps@H@@SAHAEBU?$atomic@H@std@@@Z ; QAtomicOps<int>::load<int>
	add	rsp, 40					; 00000028H
	ret	0
?load@?$QBasicAtomicInteger@H@@QEBAHXZ ENDP		; QBasicAtomicInteger<int>::load
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z
_TEXT	SEGMENT
_Atom$ = 48
_Value$ = 56
?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z PROC	; std::atomic_fetch_add, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic
; Line 919
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 920
	mov	r8d, 5
	mov	edx, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Atom$[rsp]
	call	?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z ; std::atomic_fetch_add_explicit
; Line 921
	add	rsp, 40					; 00000028H
	ret	0
?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z ENDP	; std::atomic_fetch_add
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z
_TEXT	SEGMENT
$T1 = 32
_Atom$ = 64
_Value$ = 72
_Order$ = 80
?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z PROC ; std::atomic_fetch_add_explicit, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic
; Line 909
$LN3:
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
	mov	QWORD PTR $T1[rsp], -2
; Line 910
	mov	rax, QWORD PTR _Atom$[rsp]
	mov	r8d, DWORD PTR _Order$[rsp]
	mov	edx, DWORD PTR _Value$[rsp]
	mov	rcx, rax
	call	?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z ; std::_Atomic_fetch_add_4
	npad	1
; Line 911
	add	rsp, 56					; 00000038H
	ret	0
?atomic_fetch_add_explicit@std@@YAHPEAU_Atomic_int@1@HW4memory_order@1@@Z ENDP ; std::atomic_fetch_add_explicit
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z
_TEXT	SEGMENT
$T1 = 32
_Atom$ = 64
_Order$ = 72
?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z PROC ; std::atomic_load_explicit, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic
; Line 494
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
	mov	QWORD PTR $T1[rsp], -2
; Line 495
	mov	rax, QWORD PTR _Atom$[rsp]
	mov	edx, DWORD PTR _Order$[rsp]
	mov	rcx, rax
	call	?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z ; std::_Atomic_load_4
	npad	1
; Line 496
	add	rsp, 56					; 00000038H
	ret	0
?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z ENDP ; std::atomic_load_explicit
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??E_Atomic_int@std@@QEAAHXZ
_TEXT	SEGMENT
this$ = 48
??E_Atomic_int@std@@QEAAHXZ PROC			; std::_Atomic_int::operator++, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic
; Line 1034
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 1035
	mov	edx, 1
	mov	rcx, QWORD PTR this$[rsp]
	call	?atomic_fetch_add@std@@YAHPEAU_Atomic_int@1@H@Z ; std::atomic_fetch_add
	inc	eax
; Line 1036
	add	rsp, 40					; 00000028H
	ret	0
??E_Atomic_int@std@@QEAAHXZ ENDP			; std::_Atomic_int::operator++
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z
_TEXT	SEGMENT
this$ = 48
_Order$ = 56
?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z PROC	; std::_Atomic_int::load, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic
; Line 628
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 629
	mov	edx, DWORD PTR _Order$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?atomic_load_explicit@std@@YAHPEBU_Atomic_int@1@W4memory_order@1@@Z ; std::atomic_load_explicit
; Line 630
	add	rsp, 40					; 00000028H
	ret	0
?load@_Atomic_int@std@@QEBAHW4memory_order@2@@Z ENDP	; std::_Atomic_int::load
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z
_TEXT	SEGMENT
tv64 = 48
_Tgt$ = 80
_Value$ = 88
_Order$ = 96
?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z PROC ; std::_Atomic_fetch_add_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1570
$LN15:
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 1571
	mov	eax, DWORD PTR _Order$[rsp]
	mov	DWORD PTR tv64[rsp], eax
	cmp	DWORD PTR tv64[rsp], 5
	ja	SHORT $LN11@Atomic_fet
	movsxd	rax, DWORD PTR tv64[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN14@Atomic_fet[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN7@Atomic_fet:
; Line 1574
	mov	edx, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Fetch_add_relaxed_4@std@@YAKPECKK@Z	; std::_Fetch_add_relaxed_4
	jmp	$LN1@Atomic_fet
$LN8@Atomic_fet:
; Line 1578
	mov	edx, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Fetch_add_acquire_4@std@@YAKPECKK@Z	; std::_Fetch_add_acquire_4
	jmp	$LN1@Atomic_fet
$LN9@Atomic_fet:
; Line 1581
	mov	edx, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Fetch_add_release_4@std@@YAKPECKK@Z	; std::_Fetch_add_release_4
	jmp	SHORT $LN1@Atomic_fet
$LN10@Atomic_fet:
; Line 1585
	mov	edx, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Fetch_add_seq_cst_4@std@@YAKPECKK@Z	; std::_Fetch_add_seq_cst_4
	jmp	SHORT $LN1@Atomic_fet
$LN11@Atomic_fet:
$LN6@Atomic_fet:
; Line 1588
	lea	rax, OFFSET FLAT:??_C@_0BF@ELBANHFK@Invalid?5memory_order@
	mov	QWORD PTR [rsp+40], rax
	lea	rax, OFFSET FLAT:??_C@_02DKCKIIND@?$CFs@
	mov	QWORD PTR [rsp+32], rax
	xor	r9d, r9d
	mov	r8d, 1588				; 00000634H
	lea	rdx, OFFSET FLAT:??_C@_0GK@HCPCNJPA@c?3?2program?5files?5?$CIx86?$CJ?2microsof@
	mov	ecx, 2
	call	QWORD PTR __imp__CrtDbgReport
	cmp	eax, 1
	jne	SHORT $LN13@Atomic_fet
	int	3
	xor	eax, eax
$LN13@Atomic_fet:
	mov	QWORD PTR [rsp+32], 0
	mov	r9d, 1588				; 00000634H
	lea	r8, OFFSET FLAT:??_C@_1NE@JIAMEJOL@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe@
	lea	rdx, OFFSET FLAT:??_C@_1DC@FMPHIJPC@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAf?$AAe@
	lea	rcx, OFFSET FLAT:??_C@_1CO@MPEJOJHF@?$AA?$CC?$AAI?$AAn?$AAv?$AAa?$AAl?$AAi?$AAd?$AA?5?$AAm?$AAe?$AAm?$AAo?$AAr?$AAy@
	call	QWORD PTR __imp__invalid_parameter
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN6@Atomic_fet
; Line 1589
	xor	eax, eax
$LN1@Atomic_fet:
; Line 1591
	add	rsp, 72					; 00000048H
	ret	0
	npad	3
$LN14@Atomic_fet:
	DD	$LN7@Atomic_fet
	DD	$LN8@Atomic_fet
	DD	$LN8@Atomic_fet
	DD	$LN9@Atomic_fet
	DD	$LN10@Atomic_fet
	DD	$LN10@Atomic_fet
?_Atomic_fetch_add_4@std@@YAKPECKKW4memory_order@1@@Z ENDP ; std::_Atomic_fetch_add_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Fetch_add_release_4@std@@YAKPECKK@Z
_TEXT	SEGMENT
_Tgt$ = 8
_Value$ = 16
?_Fetch_add_release_4@std@@YAKPECKK@Z PROC		; std::_Fetch_add_release_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1562
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 1564
	mov	eax, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	lock xadd DWORD PTR [rcx], eax
; Line 1566
	ret	0
?_Fetch_add_release_4@std@@YAKPECKK@Z ENDP		; std::_Fetch_add_release_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Fetch_add_acquire_4@std@@YAKPECKK@Z
_TEXT	SEGMENT
_Tgt$ = 8
_Value$ = 16
?_Fetch_add_acquire_4@std@@YAKPECKK@Z PROC		; std::_Fetch_add_acquire_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1555
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 1557
	mov	eax, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	lock xadd DWORD PTR [rcx], eax
; Line 1559
	ret	0
?_Fetch_add_acquire_4@std@@YAKPECKK@Z ENDP		; std::_Fetch_add_acquire_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Fetch_add_relaxed_4@std@@YAKPECKK@Z
_TEXT	SEGMENT
_Tgt$ = 8
_Value$ = 16
?_Fetch_add_relaxed_4@std@@YAKPECKK@Z PROC		; std::_Fetch_add_relaxed_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1548
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 1550
	mov	eax, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	lock xadd DWORD PTR [rcx], eax
; Line 1552
	ret	0
?_Fetch_add_relaxed_4@std@@YAKPECKK@Z ENDP		; std::_Fetch_add_relaxed_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Fetch_add_seq_cst_4@std@@YAKPECKK@Z
_TEXT	SEGMENT
_Tgt$ = 8
_Value$ = 16
?_Fetch_add_seq_cst_4@std@@YAKPECKK@Z PROC		; std::_Fetch_add_seq_cst_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1541
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 1543
	mov	eax, DWORD PTR _Value$[rsp]
	mov	rcx, QWORD PTR _Tgt$[rsp]
	lock xadd DWORD PTR [rcx], eax
; Line 1545
	ret	0
?_Fetch_add_seq_cst_4@std@@YAKPECKK@Z ENDP		; std::_Fetch_add_seq_cst_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z
_TEXT	SEGMENT
tv64 = 48
_Tgt$ = 80
_Order$ = 88
?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z PROC	; std::_Atomic_load_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1356
$LN13:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 1357
	mov	eax, DWORD PTR _Order$[rsp]
	mov	DWORD PTR tv64[rsp], eax
	cmp	DWORD PTR tv64[rsp], 0
	je	SHORT $LN7@Atomic_loa
	cmp	DWORD PTR tv64[rsp], 0
	jle	SHORT $LN10@Atomic_loa
	cmp	DWORD PTR tv64[rsp], 2
	jle	SHORT $LN8@Atomic_loa
	cmp	DWORD PTR tv64[rsp], 5
	je	SHORT $LN9@Atomic_loa
	jmp	SHORT $LN10@Atomic_loa
$LN7@Atomic_loa:
; Line 1360
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Load_relaxed_4@std@@YAKPECK@Z		; std::_Load_relaxed_4
	jmp	$LN1@Atomic_loa
$LN8@Atomic_loa:
; Line 1364
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Load_acquire_4@std@@YAKPECK@Z		; std::_Load_acquire_4
	jmp	SHORT $LN1@Atomic_loa
$LN9@Atomic_loa:
; Line 1367
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Load_seq_cst_4@std@@YAKPECK@Z		; std::_Load_seq_cst_4
	jmp	SHORT $LN1@Atomic_loa
$LN10@Atomic_loa:
$LN6@Atomic_loa:
; Line 1372
	lea	rax, OFFSET FLAT:??_C@_0BF@ELBANHFK@Invalid?5memory_order@
	mov	QWORD PTR [rsp+40], rax
	lea	rax, OFFSET FLAT:??_C@_02DKCKIIND@?$CFs@
	mov	QWORD PTR [rsp+32], rax
	xor	r9d, r9d
	mov	r8d, 1372				; 0000055cH
	lea	rdx, OFFSET FLAT:??_C@_0GK@HCPCNJPA@c?3?2program?5files?5?$CIx86?$CJ?2microsof@
	mov	ecx, 2
	call	QWORD PTR __imp__CrtDbgReport
	cmp	eax, 1
	jne	SHORT $LN12@Atomic_loa
	int	3
	xor	eax, eax
$LN12@Atomic_loa:
	mov	QWORD PTR [rsp+32], 0
	mov	r9d, 1372				; 0000055cH
	lea	r8, OFFSET FLAT:??_C@_1NE@JIAMEJOL@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe@
	lea	rdx, OFFSET FLAT:??_C@_1CI@NMHCEFB@?$AAs?$AAt?$AAd?$AA?3?$AA?3?$AA_?$AAA?$AAt?$AAo?$AAm?$AAi?$AAc?$AA_?$AAl?$AAo@
	lea	rcx, OFFSET FLAT:??_C@_1CO@MPEJOJHF@?$AA?$CC?$AAI?$AAn?$AAv?$AAa?$AAl?$AAi?$AAd?$AA?5?$AAm?$AAe?$AAm?$AAo?$AAr?$AAy@
	call	QWORD PTR __imp__invalid_parameter
	xor	eax, eax
	test	eax, eax
	jne	SHORT $LN6@Atomic_loa
; Line 1373
	xor	eax, eax
$LN1@Atomic_loa:
; Line 1375
	add	rsp, 72					; 00000048H
	ret	0
?_Atomic_load_4@std@@YAKPECKW4memory_order@1@@Z ENDP	; std::_Atomic_load_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Load_acquire_4@std@@YAKPECK@Z
_TEXT	SEGMENT
_Tgt$ = 48
?_Load_acquire_4@std@@YAKPECK@Z PROC			; std::_Load_acquire_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1348
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 1351
	mov	rcx, QWORD PTR _Tgt$[rsp]
	call	?_Load_seq_cst_4@std@@YAKPECK@Z		; std::_Load_seq_cst_4
; Line 1352
	add	rsp, 40					; 00000028H
	ret	0
?_Load_acquire_4@std@@YAKPECK@Z ENDP			; std::_Load_acquire_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Load_relaxed_4@std@@YAKPECK@Z
_TEXT	SEGMENT
_Value$ = 0
_Tgt$ = 32
?_Load_relaxed_4@std@@YAKPECK@Z PROC			; std::_Load_relaxed_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1333
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 1341
	mov	rax, QWORD PTR _Tgt$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR _Value$[rsp], eax
; Line 1344
	mov	eax, DWORD PTR _Value$[rsp]
; Line 1345
	add	rsp, 24
	ret	0
?_Load_relaxed_4@std@@YAKPECK@Z ENDP			; std::_Load_relaxed_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?_Load_seq_cst_4@std@@YAKPECK@Z
_TEXT	SEGMENT
_Value$ = 0
_Tgt$ = 32
?_Load_seq_cst_4@std@@YAKPECK@Z PROC			; std::_Load_seq_cst_4, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xatomic.h
; Line 1316
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 1325
	mov	rax, QWORD PTR _Tgt$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR _Value$[rsp], eax
; Line 1329
	mov	eax, DWORD PTR _Value$[rsp]
; Line 1330
	add	rsp, 24
	ret	0
?_Load_seq_cst_4@std@@YAKPECK@Z ENDP			; std::_Load_seq_cst_4
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??2@YAPEAX_KPEAX@Z
_TEXT	SEGMENT
_Size$ = 8
_Where$ = 16
??2@YAPEAX_KPEAX@Z PROC					; operator new, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\vcruntime_new.h
; Line 185
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 187
	mov	rax, QWORD PTR _Where$[rsp]
; Line 188
	ret	0
??2@YAPEAX_KPEAX@Z ENDP					; operator new
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xchartwindow.cpp
; Line 136
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xchartwindow.cpp
; Line 136
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
