; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG164611 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG164612 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG164613 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG167655 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG167656 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG167657 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG168016 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG168017 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG168018 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG168377 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG168378 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG168379 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_xNewDialog@@3Uqt_meta_stringdata_xNewDialog_t@@B DD 0ffffffffH ; qt_meta_stringdata_xNewDialog
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000053H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000044H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	000000000000002dH
	DB	078H
	DB	04eH
	DB	065H
	DB	077H
	DB	044H
	DB	069H
	DB	061H
	DB	06cH
	DB	06fH
	DB	067H
	DB	00H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	05fH
	DB	06fH
	DB	06bH
	DB	00H
	DB	00H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	05fH
	DB	062H
	DB	072H
	DB	06fH
	DB	077H
	DB	073H
	DB	065H
	DB	00H
	ORG $+6
	ORG $+8
?qt_meta_data_xNewDialog@@3QBIB DD 08H			; qt_meta_data_xNewDialog
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	019H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG169220 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG169221 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG169222 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG169581 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG169582 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG169583 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG169942 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG169943 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG169944 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG170352 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG170353 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG170354 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@xNewDialog@@UEBAPEBUQMetaObject@@XZ	; xNewDialog::metaObject
PUBLIC	?qt_metacast@xNewDialog@@UEAAPEAXPEBD@Z		; xNewDialog::qt_metacast
PUBLIC	?qt_metacall@xNewDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xNewDialog::qt_metacall
PUBLIC	?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xNewDialog::qt_static_metacall
PUBLIC	?staticMetaObject@xNewDialog@@2UQMetaObject@@B	; xNewDialog::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?Click_ok@xNewDialog@@AEAAXXZ:PROC		; xNewDialog::Click_ok
EXTRN	?Click_browse@xNewDialog@@AEAAXXZ:PROC		; xNewDialog::Click_browse
EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@xNewDialog@@2UQMetaObject@@B DB 030H DUP (?) ; xNewDialog::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@xNewDialog@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@xNewDialog@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@xNewDialog@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@xNewDialog@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@xNewDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@xNewDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+91
	DD	imagerel $unwind$?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xNewDialog@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xNewDialog@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xNewDialog@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@xNewDialog@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@xNewDialog@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@xNewDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@xNewDialog@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xNewDialog@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xNewDialog::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xnewdialog.cpp
; Line 83
	mov	rax, QWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xNewDialog@@2UQMetaObject@@B, rax
; Line 84
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_xNewDialog@@3Uqt_meta_stringdata_xNewDialog_t@@B
	mov	QWORD PTR ?staticMetaObject@xNewDialog@@2UQMetaObject@@B+8, rax
; Line 85
	lea	rax, OFFSET FLAT:?qt_meta_data_xNewDialog@@3QBIB
	mov	QWORD PTR ?staticMetaObject@xNewDialog@@2UQMetaObject@@B+16, rax
; Line 86
	lea	rax, OFFSET FLAT:?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xNewDialog::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@xNewDialog@@2UQMetaObject@@B+24, rax
; Line 87
	mov	QWORD PTR ?staticMetaObject@xNewDialog@@2UQMetaObject@@B+32, 0
; Line 88
	mov	QWORD PTR ?staticMetaObject@xNewDialog@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@xNewDialog@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xNewDialog::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xNewDialog::qt_static_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xnewdialog.cpp
; Line 69
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 70
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 71
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 73
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN5@qt_static_:
; Line 74
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?Click_ok@xNewDialog@@AEAAXXZ		; xNewDialog::Click_ok
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 75
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?Click_browse@xNewDialog@@AEAAXXZ	; xNewDialog::Click_browse
$LN7@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 80
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xNewDialog::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xNewDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xNewDialog::qt_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xnewdialog.cpp
; Line 106
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 107
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 108
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 109
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 110
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 111
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 112
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@xNewDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xNewDialog::qt_static_metacall
$LN5@qt_metacal:
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 114
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 115
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 116
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 117
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 120
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@xNewDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xNewDialog::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@xNewDialog@@UEAAPEAXPEBD@Z PROC		; xNewDialog::qt_metacast
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xnewdialog.cpp
; Line 98
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 99
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 100
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_xNewDialog@@3Uqt_meta_stringdata_xNewDialog_t@@B+96
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 101
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 102
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 103
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@xNewDialog@@UEAAPEAXPEBD@Z ENDP		; xNewDialog::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@xNewDialog@@UEBAPEBUQMetaObject@@XZ PROC	; xNewDialog::metaObject
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xnewdialog.cpp
; Line 93
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 94
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xNewDialog@@2UQMetaObject@@B ; xNewDialog::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 95
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@xNewDialog@@UEBAPEBUQMetaObject@@XZ ENDP	; xNewDialog::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xnewdialog.cpp
; Line 123
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xnewdialog.cpp
; Line 123
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
