; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG139394 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG139395 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG139396 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_xResultCallThread@@3Uqt_meta_stringdata_xResultCallThread_t@@B DD 0ffffffffH ; qt_meta_stringdata_xResultCallThread
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000005aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000055H
	DD	0ffffffffH
	DD	019H
	DD	00H
	ORG $+4
	DQ	000000000000003eH
	DB	078H
	DB	052H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	043H
	DB	061H
	DB	06cH
	DB	06cH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	DB	072H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	05fH
	DB	063H
	DB	061H
	DB	06cH
	DB	06cH
	DB	05fH
	DB	066H
	DB	069H
	DB	06eH
	DB	069H
	DB	073H
	DB	068H
	DB	00H
	DB	00H
	DB	072H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	05fH
	DB	063H
	DB	061H
	DB	06cH
	DB	06cH
	DB	05fH
	DB	073H
	DB	065H
	DB	06eH
	DB	064H
	DB	05fH
	DB	070H
	DB	072H
	DB	06fH
	DB	067H
	DB	072H
	DB	065H
	DB	073H
	DB	073H
	DB	00H
?qt_meta_data_xResultCallThread@@3QBIB DD 08H		; qt_meta_data_xResultCallThread
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	06H
	DD	03H
	DD	02H
	DD	019H
	DD	02H
	DD	06H
	DD	02bH
	DD	02bH
	DD	02H
	DD	0aH
	DD	02H
	DD	02H
	DD	00H
	ORG $+4
$SG138672 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG138673 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138674 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG139033 DB	'c:\qt\5.12.3\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG139034 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG139035 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@xResultCallThread@@UEBAPEBUQMetaObject@@XZ ; xResultCallThread::metaObject
PUBLIC	?qt_metacast@xResultCallThread@@UEAAPEAXPEBD@Z	; xResultCallThread::qt_metacast
PUBLIC	?qt_metacall@xResultCallThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xResultCallThread::qt_metacall
PUBLIC	?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xResultCallThread::qt_static_metacall
PUBLIC	?result_call_finish@xResultCallThread@@QEAAXXZ	; xResultCallThread::result_call_finish
PUBLIC	?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z ; xResultCallThread::result_call_send_progress
PUBLIC	?staticMetaObject@xResultCallThread@@2UQMetaObject@@B ; xResultCallThread::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_??1QString@@QEAA@XZ:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QThread@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__GSHandlerCheck_EH:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp_?staticMetaObject@QThread@@2UQMetaObject@@B:BYTE
EXTRN	__security_cookie:QWORD
_BSS	SEGMENT
?staticMetaObject@xResultCallThread@@2UQMetaObject@@B DB 030H DUP (?) ; xResultCallThread::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@xResultCallThread@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@xResultCallThread@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@xResultCallThread@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@xResultCallThread@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@xResultCallThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@xResultCallThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN14
	DD	imagerel $LN14+276
	DD	imagerel $unwind$?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?result_call_finish@xResultCallThread@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?result_call_finish@xResultCallThread@@QEAAXXZ
$pdata$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z DD imagerel $LN4
	DD	imagerel $LN4+130
	DD	imagerel $unwind$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z
pdata	ENDS
pdata	SEGMENT
$pdata$?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA DD imagerel ?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA
	DD	imagerel ?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA+25
	DD	imagerel $unwind$?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xResultCallThread@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xResultCallThread@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xResultCallThread@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
CONST	SEGMENT
	ORG $+4
$cppxdata$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z
	DD	00H
	DD	00H
	DD	03H
	DD	imagerel $ip2state$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z
	DD	020H
	DD	00H
	DD	01H
CONST	ENDS
xdata	SEGMENT
$unwind$?metaObject@xResultCallThread@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@xResultCallThread@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@xResultCallThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0a217H
$unwind$?result_call_finish@xResultCallThread@@QEAAXXZ DD 010901H
	DD	04209H
$unwind$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z DD 012a19H
	DD	0a212H
	DD	imagerel __GSHandlerCheck_EH
	DD	imagerel $cppxdata$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z
	DD	042H
$stateUnwindMap$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA
$ip2state$?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z DD imagerel ?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z
	DD	0ffffffffH
	DD	imagerel ?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z+42
	DD	00H
	DD	imagerel ?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z+101
	DD	0ffffffffH
$unwind$?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA DD 020601H
	DD	050023206H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@xResultCallThread@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xResultCallThread@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xResultCallThread::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 99
	mov	rax, QWORD PTR __imp_?staticMetaObject@QThread@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xResultCallThread@@2UQMetaObject@@B, rax
; Line 100
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_xResultCallThread@@3Uqt_meta_stringdata_xResultCallThread_t@@B
	mov	QWORD PTR ?staticMetaObject@xResultCallThread@@2UQMetaObject@@B+8, rax
; Line 101
	lea	rax, OFFSET FLAT:?qt_meta_data_xResultCallThread@@3QBIB
	mov	QWORD PTR ?staticMetaObject@xResultCallThread@@2UQMetaObject@@B+16, rax
; Line 102
	lea	rax, OFFSET FLAT:?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xResultCallThread::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@xResultCallThread@@2UQMetaObject@@B+24, rax
; Line 103
	mov	QWORD PTR ?staticMetaObject@xResultCallThread@@2UQMetaObject@@B+32, 0
; Line 104
	mov	QWORD PTR ?staticMetaObject@xResultCallThread@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@xResultCallThread@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xResultCallThread::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 64
this$ = 96
_t1$ = 104
_t2$ = 112
?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z PROC ; xResultCallThread::result_call_send_progress
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 146
$LN4:
	mov	QWORD PTR [rsp+24], r8
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
	mov	QWORD PTR $T1[rsp], -2
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
; Line 147
	mov	QWORD PTR _a$[rsp], 0
	lea	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	mov	rax, QWORD PTR _t2$[rsp]
	mov	QWORD PTR _a$[rsp+16], rax
; Line 148
	lea	r9, QWORD PTR _a$[rsp]
	mov	r8d, 1
	lea	rdx, OFFSET FLAT:?staticMetaObject@xResultCallThread@@2UQMetaObject@@B ; xResultCallThread::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
	npad	1
; Line 149
	mov	rcx, QWORD PTR _t2$[rsp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 88					; 00000058H
	ret	0
?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z ENDP ; xResultCallThread::result_call_send_progress
_TEXT	ENDS
text$x	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 64
this$ = 96
_t1$ = 104
_t2$ = 112
?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA PROC ; `xResultCallThread::result_call_send_progress'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR _t2$[rbp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA ENDP ; `xResultCallThread::result_call_send_progress'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
text$x	SEGMENT
$T1 = 32
_a$ = 40
__$ArrayPad$ = 64
this$ = 96
_t1$ = 104
_t2$ = 112
?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA PROC ; `xResultCallThread::result_call_send_progress'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	rcx, QWORD PTR _t2$[rbp]
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z@4HA ENDP ; `xResultCallThread::result_call_send_progress'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?result_call_finish@xResultCallThread@@QEAAXXZ PROC	; xResultCallThread::result_call_finish
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 140
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 141
	xor	r9d, r9d
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xResultCallThread@@2UQMetaObject@@B ; xResultCallThread::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 142
	add	rsp, 40					; 00000028H
	ret	0
?result_call_finish@xResultCallThread@@QEAAXXZ ENDP	; xResultCallThread::result_call_finish
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
result$2 = 48
$T3 = 56
tv133 = 64
$T4 = 72
_o$ = 96
_c$ = 104
_id$ = 112
_a$ = 120
?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xResultCallThread::qt_static_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 70
$LN14:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
; Line 71
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 72
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 74
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 75
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?result_call_finish@xResultCallThread@@QEAAXXZ ; xResultCallThread::result_call_finish
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 76
	lea	rax, QWORD PTR $T4[rsp]
	mov	QWORD PTR $T3[rsp], rax
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	QWORD PTR tv133[rsp], rax
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	r8, QWORD PTR tv133[rsp]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z ; xResultCallThread::result_call_send_progress
$LN2@qt_static_:
; Line 79
	jmp	SHORT $LN1@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	SHORT $LN1@qt_static_
; Line 80
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 83
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	lea	rcx, OFFSET FLAT:?result_call_finish@xResultCallThread@@QEAAXXZ ; xResultCallThread::result_call_finish
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN10@qt_static_
; Line 84
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
; Line 85
	jmp	SHORT $LN1@qt_static_
$LN10@qt_static_:
; Line 90
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	lea	rcx, OFFSET FLAT:?result_call_send_progress@xResultCallThread@@QEAAXHVQString@@@Z ; xResultCallThread::result_call_send_progress
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN1@qt_static_
; Line 91
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 1
$LN1@qt_static_:
; Line 96
	add	rsp, 88					; 00000058H
	ret	0
?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xResultCallThread::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xResultCallThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xResultCallThread::qt_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 122
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 123
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 124
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 125
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 126
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 127
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 128
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@xResultCallThread@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xResultCallThread::qt_static_metacall
$LN5@qt_metacal:
; Line 129
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 130
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 131
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 132
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 133
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 135
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 136
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@xResultCallThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xResultCallThread::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@xResultCallThread@@UEAAPEAXPEBD@Z PROC	; xResultCallThread::qt_metacast
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 114
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 115
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 116
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_xResultCallThread@@3Uqt_meta_stringdata_xResultCallThread_t@@B+96
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 117
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 118
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QThread@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 119
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@xResultCallThread@@UEAAPEAXPEBD@Z ENDP	; xResultCallThread::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@xResultCallThread@@UEBAPEBUQMetaObject@@XZ PROC ; xResultCallThread::metaObject
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 109
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 110
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xResultCallThread@@2UQMetaObject@@B ; xResultCallThread::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 111
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@xResultCallThread@@UEBAPEBUQMetaObject@@XZ ENDP ; xResultCallThread::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 152
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xresultcallthread.cpp
; Line 152
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
