; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG150116 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG150117 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG150118 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG150477 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG150478 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG150479 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG150838 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG150839 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG150840 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG151692 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG151693 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG151694 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_xAnimationTool@@3Uqt_meta_stringdata_xAnimationTool_t@@B DD 0ffffffffH ; qt_meta_stringdata_xAnimationTool
	DD	0eH
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000006fH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000006aH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000053H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000051H
	DB	078H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	054H
	DB	06fH
	DB	06fH
	DB	06cH
	DB	00H
	DB	078H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	04fH
	DB	070H
	DB	065H
	DB	072H
	DB	061H
	DB	074H
	DB	06fH
	DB	072H
	DB	00H
	DB	00H
	DB	078H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	046H
	DB	072H
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	DB	078H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	053H
	DB	06cH
	DB	069H
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	ORG $+8
?qt_meta_data_xAnimationTool@@3QBIB DD 08H		; qt_meta_data_xAnimationTool
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	01dH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	01eH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	01fH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG147136 DB	'c:\qt\5.12.6\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+4
$SG147137 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG147138 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ ; xAnimationTool::metaObject
PUBLIC	?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z	; xAnimationTool::qt_metacast
PUBLIC	?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xAnimationTool::qt_metacall
PUBLIC	?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xAnimationTool::qt_static_metacall
PUBLIC	?staticMetaObject@xAnimationTool@@2UQMetaObject@@B ; xAnimationTool::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QToolBar@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QToolBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?xAnimationOperator@xAnimationTool@@AEAAXXZ:PROC ; xAnimationTool::xAnimationOperator
EXTRN	?xChangeAnimationFrame@xAnimationTool@@AEAAXXZ:PROC ; xAnimationTool::xChangeAnimationFrame
EXTRN	?xChangeAnimationSlider@xAnimationTool@@AEAAXXZ:PROC ; xAnimationTool::xChangeAnimationSlider
EXTRN	__imp_?staticMetaObject@QToolBar@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@xAnimationTool@@2UQMetaObject@@B DB 030H DUP (?) ; xAnimationTool::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+110
	DD	imagerel $unwind$?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xAnimationTool@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xAnimationTool@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xAnimationTool::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xanimationtool.cpp
; Line 88
	mov	rax, QWORD PTR __imp_?staticMetaObject@QToolBar@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xAnimationTool@@2UQMetaObject@@B, rax
; Line 89
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_xAnimationTool@@3Uqt_meta_stringdata_xAnimationTool_t@@B
	mov	QWORD PTR ?staticMetaObject@xAnimationTool@@2UQMetaObject@@B+8, rax
; Line 90
	lea	rax, OFFSET FLAT:?qt_meta_data_xAnimationTool@@3QBIB
	mov	QWORD PTR ?staticMetaObject@xAnimationTool@@2UQMetaObject@@B+16, rax
; Line 91
	lea	rax, OFFSET FLAT:?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xAnimationTool::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@xAnimationTool@@2UQMetaObject@@B+24, rax
; Line 92
	mov	QWORD PTR ?staticMetaObject@xAnimationTool@@2UQMetaObject@@B+32, 0
; Line 93
	mov	QWORD PTR ?staticMetaObject@xAnimationTool@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xAnimationTool::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xAnimationTool::qt_static_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xanimationtool.cpp
; Line 73
$LN10:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 74
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 75
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 77
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	jmp	SHORT $LN8@qt_static_
$LN5@qt_static_:
; Line 78
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?xAnimationOperator@xAnimationTool@@AEAAXXZ ; xAnimationTool::xAnimationOperator
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 79
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?xChangeAnimationFrame@xAnimationTool@@AEAAXXZ ; xAnimationTool::xChangeAnimationFrame
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 80
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?xChangeAnimationSlider@xAnimationTool@@AEAAXXZ ; xAnimationTool::xChangeAnimationSlider
$LN8@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 85
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xAnimationTool::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xAnimationTool::qt_metacall
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xanimationtool.cpp
; Line 111
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 112
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QToolBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 113
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 114
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 115
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 116
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 117
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xAnimationTool::qt_static_metacall
$LN5@qt_metacal:
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 119
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 120
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 121
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 124
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 125
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xAnimationTool::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z PROC	; xAnimationTool::qt_metacast
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xanimationtool.cpp
; Line 103
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 104
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 105
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_xAnimationTool@@3Uqt_meta_stringdata_xAnimationTool_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 106
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 107
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QToolBar@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 108
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z ENDP	; xAnimationTool::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ PROC ; xAnimationTool::metaObject
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xanimationtool.cpp
; Line 98
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 99
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xAnimationTool@@2UQMetaObject@@B ; xAnimationTool::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 100
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ ENDP ; xAnimationTool::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.6\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xanimationtool.cpp
; Line 128
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\debug\moc_xanimationtool.cpp
; Line 128
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
