; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QToolBar@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_xAnimationTool@@3Uqt_meta_stringdata_xAnimationTool_t@@B DD 0ffffffffH ; qt_meta_stringdata_xAnimationTool
	DD	0eH
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000006fH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000006aH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000053H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000051H
	DB	078H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	054H
	DB	06fH
	DB	06fH
	DB	06cH
	DB	00H
	DB	078H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	04fH
	DB	070H
	DB	065H
	DB	072H
	DB	061H
	DB	074H
	DB	06fH
	DB	072H
	DB	00H
	DB	00H
	DB	078H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	046H
	DB	072H
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	DB	078H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	053H
	DB	06cH
	DB	069H
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	ORG $+8
?qt_meta_data_xAnimationTool@@3QBIB DD 08H		; qt_meta_data_xAnimationTool
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	01dH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	01eH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	01fH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ ; xAnimationTool::metaObject
PUBLIC	?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z	; xAnimationTool::qt_metacast
PUBLIC	?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xAnimationTool::qt_metacall
PUBLIC	?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xAnimationTool::qt_static_metacall
PUBLIC	?staticMetaObject@xAnimationTool@@2UQMetaObject@@B ; xAnimationTool::staticMetaObject
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QToolBar@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QToolBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?xAnimationOperator@xAnimationTool@@AEAAXXZ:PROC ; xAnimationTool::xAnimationOperator
EXTRN	?xChangeAnimationFrame@xAnimationTool@@AEAAXXZ:PROC ; xAnimationTool::xChangeAnimationFrame
EXTRN	?xChangeAnimationSlider@xAnimationTool@@AEAAXXZ:PROC ; xAnimationTool::xChangeAnimationSlider
;	COMDAT pdata
pdata	SEGMENT
$pdata$?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN19
	DD	imagerel $LN19+142
	DD	imagerel $unwind$?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xAnimationTool@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xAnimationTool@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@xAnimationTool@@2UQMetaObject@@B DB 8 DUP(00H) ; xAnimationTool::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_xAnimationTool@@3Uqt_meta_stringdata_xAnimationTool_t@@B
	DQ	FLAT:?qt_meta_data_xAnimationTool@@3QBIB
	DQ	FLAT:?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
_DATA	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 081501H
	DD	087415H
	DD	076415H
	DD	063415H
	DD	0e0113215H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xAnimationTool::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xanimationtool.cpp
; Line 88
	mov	rax, QWORD PTR __imp_?staticMetaObject@QToolBar@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xAnimationTool@@2UQMetaObject@@B, rax
; Line 93
	ret	0
??__E?staticMetaObject@xAnimationTool@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xAnimationTool::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xAnimationTool::qt_static_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xanimationtool.cpp
; Line 74
	test	edx, edx
	jne	SHORT $LN8@qt_static_
; Line 77
	test	r8d, r8d
	je	SHORT $LN5@qt_static_
	sub	r8d, 1
	je	SHORT $LN6@qt_static_
	cmp	r8d, 1
	jne	SHORT $LN8@qt_static_
; Line 80
	jmp	?xChangeAnimationSlider@xAnimationTool@@AEAAXXZ ; xAnimationTool::xChangeAnimationSlider
$LN6@qt_static_:
; Line 79
	jmp	?xChangeAnimationFrame@xAnimationTool@@AEAAXXZ ; xAnimationTool::xChangeAnimationFrame
$LN5@qt_static_:
; Line 78
	jmp	?xAnimationOperator@xAnimationTool@@AEAAXXZ ; xAnimationTool::xAnimationOperator
$LN8@qt_static_:
; Line 85
	ret	0
?qt_static_metacall@xAnimationTool@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xAnimationTool::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xAnimationTool::qt_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xanimationtool.cpp
; Line 111
$LN19:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rsi
	mov	QWORD PTR [rsp+24], rdi
	push	r14
	sub	rsp, 32					; 00000020H
	mov	r14, r9
	mov	esi, edx
	mov	rdi, rcx
; Line 112
	call	QWORD PTR __imp_?qt_metacall@QToolBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	ebx, eax
; Line 113
	test	eax, eax
	js	SHORT $LN1@qt_metacal
; Line 115
	test	esi, esi
	jne	SHORT $LN3@qt_metacal
; Line 116
	cmp	eax, 3
	jge	SHORT $LN7@qt_metacal
; Line 77
	mov	ecx, eax
	test	eax, eax
	je	SHORT $LN13@qt_metacal
	sub	ecx, 1
	je	SHORT $LN14@qt_metacal
	cmp	ecx, 1
	jne	SHORT $LN7@qt_metacal
; Line 80
	mov	rcx, rdi
	call	?xChangeAnimationSlider@xAnimationTool@@AEAAXXZ ; xAnimationTool::xChangeAnimationSlider
	jmp	SHORT $LN7@qt_metacal
$LN14@qt_metacal:
; Line 79
	mov	rcx, rdi
	call	?xChangeAnimationFrame@xAnimationTool@@AEAAXXZ ; xAnimationTool::xChangeAnimationFrame
	jmp	SHORT $LN7@qt_metacal
$LN13@qt_metacal:
; Line 78
	mov	rcx, rdi
	call	?xAnimationOperator@xAnimationTool@@AEAAXXZ ; xAnimationTool::xAnimationOperator
; Line 118
	jmp	SHORT $LN7@qt_metacal
$LN3@qt_metacal:
; Line 119
	cmp	esi, 12
	jne	SHORT $LN6@qt_metacal
; Line 120
	cmp	ebx, 3
	jge	SHORT $LN7@qt_metacal
; Line 121
	mov	rax, QWORD PTR [r14]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 124
	sub	ebx, 3
$LN6@qt_metacal:
	mov	eax, ebx
$LN1@qt_metacal:
; Line 125
	mov	rbx, QWORD PTR [rsp+48]
	mov	rsi, QWORD PTR [rsp+56]
	mov	rdi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	r14
	ret	0
?qt_metacall@xAnimationTool@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xAnimationTool::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z
_TEXT	SEGMENT
this$ = 8
_clname$ = 16
?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z PROC	; xAnimationTool::qt_metacast, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xanimationtool.cpp
; Line 103
	mov	r9, rdx
	mov	r10, rcx
; Line 104
	test	rdx, rdx
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
; Line 108
	ret	0
$LN2@qt_metacas:
; Line 105
	lea	r8, OFFSET FLAT:?qt_meta_stringdata_xAnimationTool@@3Uqt_meta_stringdata_xAnimationTool_t@@B+120
	mov	rax, r9
	sub	r8, r9
	npad	5
$LL5@qt_metacas:
	movzx	edx, BYTE PTR [rax]
	movzx	ecx, BYTE PTR [rax+r8]
	sub	edx, ecx
	jne	SHORT $LN6@qt_metacas
	inc	rax
	test	ecx, ecx
	jne	SHORT $LL5@qt_metacas
$LN6@qt_metacas:
	test	edx, edx
	jne	SHORT $LN3@qt_metacas
; Line 106
	mov	rax, r10
; Line 108
	ret	0
$LN3@qt_metacas:
; Line 107
	mov	rdx, r9
	mov	rcx, r10
	rex_jmp	QWORD PTR __imp_?qt_metacast@QToolBar@@UEAAPEAXPEBD@Z
?qt_metacast@xAnimationTool@@UEAAPEAXPEBD@Z ENDP	; xAnimationTool::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ
_TEXT	SEGMENT
this$ = 8
?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ PROC ; xAnimationTool::metaObject, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xanimationtool.cpp
; Line 99
	mov	rcx, QWORD PTR [rcx+8]
	cmp	QWORD PTR [rcx+40], 0
	je	SHORT $LN3@metaObject
	rex_jmp	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xAnimationTool@@2UQMetaObject@@B ; xAnimationTool::staticMetaObject
; Line 100
	ret	0
?metaObject@xAnimationTool@@UEBAPEBUQMetaObject@@XZ ENDP ; xAnimationTool::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 118
	mov	rax, QWORD PTR [rcx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
