; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QLineEdit@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_xLineEditWidget@@3Uqt_meta_stringdata_xLineEditWidget_t@@B DD 0ffffffffH ; qt_meta_stringdata_xLineEditWidget
	DD	0fH
	DD	00H
	ORG $+4
	DQ	0000000000000048H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000040H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000003bH
	DB	078H
	DB	04cH
	DB	069H
	DB	06eH
	DB	065H
	DB	045H
	DB	064H
	DB	069H
	DB	074H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	00H
	DB	075H
	DB	070H
	DB	05fH
	DB	061H
	DB	072H
	DB	072H
	DB	06fH
	DB	077H
	DB	05fH
	DB	06bH
	DB	065H
	DB	079H
	DB	05fH
	DB	070H
	DB	072H
	DB	065H
	DB	073H
	DB	073H
	DB	00H
	DB	00H
	ORG $+4
?qt_meta_data_xLineEditWidget@@3QBIB DD 08H		; qt_meta_data_xLineEditWidget
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	00H
	DD	013H
	DD	02H
	DD	06H
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@xLineEditWidget@@UEBAPEBUQMetaObject@@XZ ; xLineEditWidget::metaObject
PUBLIC	?qt_metacast@xLineEditWidget@@UEAAPEAXPEBD@Z	; xLineEditWidget::qt_metacast
PUBLIC	?qt_metacall@xLineEditWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xLineEditWidget::qt_metacall
PUBLIC	?qt_static_metacall@xLineEditWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xLineEditWidget::qt_static_metacall
PUBLIC	?up_arrow_key_press@xLineEditWidget@@QEAAXXZ	; xLineEditWidget::up_arrow_key_press
PUBLIC	?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B ; xLineEditWidget::staticMetaObject
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QLineEdit@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QLineEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?qt_metacall@xLineEditWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN26
	DD	imagerel $LN26+116
	DD	imagerel $unwind$?qt_metacall@xLineEditWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xLineEditWidget@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xLineEditWidget@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B DB 8 DUP(00H) ; xLineEditWidget::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_xLineEditWidget@@3Uqt_meta_stringdata_xLineEditWidget_t@@B
	DQ	FLAT:?qt_meta_data_xLineEditWidget@@3QBIB
	DQ	FLAT:?qt_static_metacall@xLineEditWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
_DATA	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?qt_metacall@xLineEditWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 081401H
	DD	086414H
	DD	075414H
	DD	063414H
	DD	070103214H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__E?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xLineEditWidget::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xlineeditwidget.cpp
; Line 88
	mov	rax, QWORD PTR __imp_?staticMetaObject@QLineEdit@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B, rax
; Line 93
	ret	0
??__E?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xLineEditWidget::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?up_arrow_key_press@xLineEditWidget@@QEAAXXZ
_TEXT	SEGMENT
this$ = 8
?up_arrow_key_press@xLineEditWidget@@QEAAXXZ PROC	; xLineEditWidget::up_arrow_key_press, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xlineeditwidget.cpp
; Line 130
	xor	r9d, r9d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B ; xLineEditWidget::staticMetaObject
	xor	r8d, r8d
	rex_jmp	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
?up_arrow_key_press@xLineEditWidget@@QEAAXXZ ENDP	; xLineEditWidget::up_arrow_key_press
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_static_metacall@xLineEditWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@xLineEditWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xLineEditWidget::qt_static_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xlineeditwidget.cpp
; Line 67
	test	edx, edx
	jne	SHORT $LN4@qt_static_
; Line 70
	test	r8d, r8d
	jne	SHORT $LN9@qt_static_
; Line 130
	xor	r9d, r9d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B ; xLineEditWidget::staticMetaObject
	rex_jmp	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
$LN4@qt_static_:
; Line 74
	cmp	edx, 10
	jne	SHORT $LN9@qt_static_
; Line 78
	mov	rax, QWORD PTR [r9+8]
	lea	r8, OFFSET FLAT:?up_arrow_key_press@xLineEditWidget@@QEAAXXZ ; xLineEditWidget::up_arrow_key_press
	mov	rdx, QWORD PTR [r9]
	mov	rcx, QWORD PTR [rax]
	cmp	rcx, r8
	jne	SHORT $LN9@qt_static_
	test	rcx, rcx
	je	SHORT $LN16@qt_static_
	cmp	DWORD PTR [rax+8], 0
	jne	SHORT $LN9@qt_static_
$LN16@qt_static_:
; Line 79
	mov	DWORD PTR [rdx], 0
$LN9@qt_static_:
; Line 85
	ret	0
?qt_static_metacall@xLineEditWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xLineEditWidget::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacall@xLineEditWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xLineEditWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xLineEditWidget::qt_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xlineeditwidget.cpp
; Line 111
$LN26:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rsi, r9
	mov	edi, edx
	mov	rbp, rcx
; Line 112
	call	QWORD PTR __imp_?qt_metacall@QLineEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	ebx, eax
; Line 113
	test	eax, eax
	js	SHORT $LN1@qt_metacal
; Line 115
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 116
	test	eax, eax
	jne	SHORT $LN7@qt_metacal
; Line 130
	xor	r9d, r9d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B ; xLineEditWidget::staticMetaObject
	xor	r8d, r8d
	mov	rcx, rbp
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 118
	jmp	SHORT $LN7@qt_metacal
$LN3@qt_metacal:
; Line 119
	cmp	edi, 12
	jne	SHORT $LN6@qt_metacal
; Line 120
	cmp	ebx, 1
	jge	SHORT $LN7@qt_metacal
; Line 121
	mov	rax, QWORD PTR [rsi]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 124
	dec	ebx
$LN6@qt_metacal:
	mov	eax, ebx
$LN1@qt_metacal:
; Line 125
	mov	rbx, QWORD PTR [rsp+48]
	mov	rbp, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?qt_metacall@xLineEditWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xLineEditWidget::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacast@xLineEditWidget@@UEAAPEAXPEBD@Z
_TEXT	SEGMENT
this$ = 8
_clname$ = 16
?qt_metacast@xLineEditWidget@@UEAAPEAXPEBD@Z PROC	; xLineEditWidget::qt_metacast, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xlineeditwidget.cpp
; Line 103
	mov	r9, rdx
	mov	r10, rcx
; Line 104
	test	rdx, rdx
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
; Line 108
	ret	0
$LN2@qt_metacas:
; Line 105
	lea	r8, OFFSET FLAT:?qt_meta_stringdata_xLineEditWidget@@3Uqt_meta_stringdata_xLineEditWidget_t@@B+72
	mov	rax, r9
	sub	r8, r9
	npad	5
$LL5@qt_metacas:
	movzx	edx, BYTE PTR [rax]
	movzx	ecx, BYTE PTR [rax+r8]
	sub	edx, ecx
	jne	SHORT $LN6@qt_metacas
	inc	rax
	test	ecx, ecx
	jne	SHORT $LL5@qt_metacas
$LN6@qt_metacas:
	test	edx, edx
	jne	SHORT $LN3@qt_metacas
; Line 106
	mov	rax, r10
; Line 108
	ret	0
$LN3@qt_metacas:
; Line 107
	mov	rdx, r9
	mov	rcx, r10
	rex_jmp	QWORD PTR __imp_?qt_metacast@QLineEdit@@UEAAPEAXPEBD@Z
?qt_metacast@xLineEditWidget@@UEAAPEAXPEBD@Z ENDP	; xLineEditWidget::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?metaObject@xLineEditWidget@@UEBAPEBUQMetaObject@@XZ
_TEXT	SEGMENT
this$ = 8
?metaObject@xLineEditWidget@@UEBAPEBUQMetaObject@@XZ PROC ; xLineEditWidget::metaObject, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xlineeditwidget.cpp
; Line 99
	mov	rcx, QWORD PTR [rcx+8]
	cmp	QWORD PTR [rcx+40], 0
	je	SHORT $LN3@metaObject
	rex_jmp	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xLineEditWidget@@2UQMetaObject@@B ; xLineEditWidget::staticMetaObject
; Line 100
	ret	0
?metaObject@xLineEditWidget@@UEBAPEBUQMetaObject@@XZ ENDP ; xLineEditWidget::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 118
	mov	rax, QWORD PTR [rcx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
