; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_xdynamics_gui@@3Uqt_meta_stringdata_xdynamics_gui_t@@B DD 0ffffffffH ; qt_meta_stringdata_xdynamics_gui
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000318H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	000000000000030eH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000002fbH
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	00000000000002e4H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	00000000000002d2H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	00000000000002c0H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	00000000000002b2H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	00000000000002a0H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	000000000000028fH
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	000000000000028cH
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000281H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	000000000000027dH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000271H
	DD	0ffffffffH
	DD	08H
	DD	00H
	ORG $+4
	DQ	000000000000026aH
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	000000000000025bH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000258H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000256H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000024fH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000248H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000243H
	DD	0ffffffffH
	DD	01aH
	DD	00H
	ORG $+4
	DQ	000000000000023dH
	DD	0ffffffffH
	DD	01fH
	DD	00H
	ORG $+4
	DQ	0000000000000240H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000248H
	DD	0ffffffffH
	DD	018H
	DD	00H
	ORG $+4
	DQ	0000000000000246H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000247H
	DD	0ffffffffH
	DD	02H
	DD	00H
	ORG $+4
	DQ	0000000000000243H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	000000000000022eH
	DD	0ffffffffH
	DD	03H
	DD	00H
	ORG $+4
	DQ	0000000000000226H
	DD	0ffffffffH
	DD	028H
	DD	00H
	ORG $+4
	DQ	0000000000000212H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000223H
	DD	0ffffffffH
	DD	025H
	DD	00H
	ORG $+4
	DQ	0000000000000222H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000230H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	000000000000022aH
	DB	078H
	DB	064H
	DB	079H
	DB	06eH
	DB	061H
	DB	06dH
	DB	069H
	DB	063H
	DB	073H
	DB	05fH
	DB	067H
	DB	075H
	DB	069H
	DB	00H
	DB	078H
	DB	04eH
	DB	065H
	DB	077H
	DB	00H
	DB	00H
	DB	078H
	DB	053H
	DB	061H
	DB	076H
	DB	065H
	DB	00H
	DB	078H
	DB	04fH
	DB	070H
	DB	065H
	DB	06eH
	DB	00H
	DB	078H
	DB	043H
	DB	079H
	DB	06cH
	DB	069H
	DB	06eH
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	DB	078H
	DB	043H
	DB	075H
	DB	062H
	DB	065H
	DB	00H
	DB	078H
	DB	043H
	DB	068H
	DB	061H
	DB	072H
	DB	074H
	DB	00H
	DB	078H
	DB	047H
	DB	065H
	DB	074H
	DB	053H
	DB	069H
	DB	06dH
	DB	075H
	DB	06cH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	00H
	DB	077H
	DB	073H
	DB	069H
	DB	06dH
	DB	075H
	DB	06cH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	02aH
	DB	00H
	DB	078H
	DB	047H
	DB	065H
	DB	074H
	DB	050H
	DB	06fH
	DB	069H
	DB	06eH
	DB	074H
	DB	04dH
	DB	061H
	DB	073H
	DB	073H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	00H
	DB	077H
	DB	070H
	DB	06fH
	DB	069H
	DB	06eH
	DB	074H
	DB	06dH
	DB	061H
	DB	073H
	DB	073H
	DB	02aH
	DB	00H
	DB	078H
	DB	047H
	DB	065H
	DB	074H
	DB	052H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	00H
	DB	077H
	DB	072H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	02aH
	DB	00H
	DB	078H
	DB	052H
	DB	075H
	DB	06eH
	DB	053H
	DB	069H
	DB	06dH
	DB	075H
	DB	06cH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	DB	078H
	DB	045H
	DB	078H
	DB	069H
	DB	074H
	DB	053H
	DB	069H
	DB	06dH
	DB	075H
	DB	06cH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	DB	078H
	DB	052H
	DB	065H
	DB	063H
	DB	069H
	DB	065H
	DB	076H
	DB	065H
	DB	050H
	DB	072H
	DB	06fH
	DB	067H
	DB	072H
	DB	065H
	DB	073H
	DB	073H
	DB	00H
	DB	078H
	DB	045H
	DB	064H
	DB	069H
	DB	074H
	DB	043H
	DB	06fH
	DB	06dH
	DB	06dH
	DB	061H
	DB	06eH
	DB	064H
	DB	04cH
	DB	069H
	DB	06eH
	DB	065H
	DB	00H
	DB	078H
	DB	047H
	DB	065H
	DB	06fH
	DB	06dH
	DB	065H
	DB	074H
	DB	072H
	DB	079H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	078H
	DB	052H
	DB	065H
	DB	06cH
	DB	065H
	DB	061H
	DB	073H
	DB	065H
	DB	04fH
	DB	070H
	DB	065H
	DB	072H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	078H
	DB	049H
	DB	06eH
	DB	069H
	DB	074H
	DB	069H
	DB	061H
	DB	06cH
	DB	069H
	DB	07aH
	DB	065H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	053H
	DB	074H
	DB	061H
	DB	074H
	DB	065H
	DB	06dH
	DB	065H
	DB	06eH
	DB	074H
	DB	00H
	DB	078H
	DB	04fH
	DB	06eH
	DB	047H
	DB	065H
	DB	06fH
	DB	06dH
	DB	065H
	DB	074H
	DB	072H
	DB	079H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	04fH
	DB	066H
	DB	050H
	DB	06fH
	DB	069H
	DB	06eH
	DB	074H
	DB	04dH
	DB	061H
	DB	073H
	DB	073H
	DB	00H
	DB	078H
	DB	053H
	DB	074H
	DB	06fH
	DB	070H
	DB	053H
	DB	069H
	DB	06dH
	DB	075H
	DB	06cH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	DB	078H
	DB	052H
	DB	065H
	DB	06cH
	DB	065H
	DB	061H
	DB	073H
	DB	065H
	DB	052H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	043H
	DB	061H
	DB	06cH
	DB	06cH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	DB	078H
	DB	043H
	DB	06fH
	DB	06eH
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	04dH
	DB	065H
	DB	06eH
	DB	075H
	DB	050H
	DB	072H
	DB	06fH
	DB	063H
	DB	065H
	DB	073H
	DB	073H
	DB	00H
	DB	06eH
	DB	06dH
	DB	00H
	DB	063H
	DB	06fH
	DB	06eH
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	04dH
	DB	065H
	DB	06eH
	DB	075H
	DB	054H
	DB	079H
	DB	070H
	DB	065H
	DB	00H
	DB	076H
	DB	06fH
	DB	074H
	DB	00H
	DB	078H
	DB	053H
	DB	065H
	DB	074H
	DB	075H
	DB	070H
	DB	052H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	04eH
	DB	061H
	DB	076H
	DB	069H
	DB	067H
	DB	061H
	DB	074H
	DB	06fH
	DB	072H
	DB	042H
	DB	079H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	054H
	DB	061H
	DB	072H
	DB	067H
	DB	065H
	DB	074H
	DB	043H
	DB	06fH
	DB	06dH
	DB	062H
	DB	06fH
	DB	00H
	DB	078H
	DB	055H
	DB	070H
	DB	06cH
	DB	06fH
	DB	061H
	DB	064H
	DB	052H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	054H
	DB	068H
	DB	069H
	DB	073H
	DB	04dH
	DB	06fH
	DB	064H
	DB	065H
	DB	06cH
	DB	00H
	DB	078H
	DB	053H
	DB	065H
	DB	074H
	DB	075H
	DB	070H
	DB	050H
	DB	061H
	DB	072H
	DB	074H
	DB	069H
	DB	063H
	DB	06cH
	DB	065H
	DB	042H
	DB	075H
	DB	066H
	DB	066H
	DB	065H
	DB	072H
	DB	043H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	044H
	DB	069H
	DB	073H
	DB	074H
	DB	072H
	DB	069H
	DB	062H
	DB	075H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	078H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	050H
	DB	06fH
	DB	069H
	DB	06eH
	DB	074H
	DB	00H
	DB	078H
	DB	050H
	DB	061H
	DB	073H
	DB	073H
	DB	044H
	DB	069H
	DB	073H
	DB	074H
	DB	072H
	DB	069H
	DB	062H
	DB	075H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	ORG $+4
?qt_meta_data_xdynamics_gui@@3QBIB DD 08H		; qt_meta_data_xdynamics_gui
	DD	00H
	DD	00H
	DD	00H
	DD	019H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	08bH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	08cH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	08dH
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	08eH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	08fH
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	090H
	DD	02H
	DD	08H
	DD	08H
	DD	01H
	DD	091H
	DD	02H
	DD	08H
	DD	0aH
	DD	01H
	DD	094H
	DD	02H
	DD	08H
	DD	0cH
	DD	01H
	DD	097H
	DD	02H
	DD	08H
	DD	0eH
	DD	03H
	DD	09aH
	DD	02H
	DD	08H
	DD	0fH
	DD	00H
	DD	0a1H
	DD	02H
	DD	08H
	DD	010H
	DD	02H
	DD	0a2H
	DD	02H
	DD	08H
	DD	011H
	DD	00H
	DD	0a7H
	DD	02H
	DD	08H
	DD	012H
	DD	01H
	DD	0a8H
	DD	02H
	DD	08H
	DD	013H
	DD	00H
	DD	0abH
	DD	02H
	DD	08H
	DD	014H
	DD	00H
	DD	0acH
	DD	02H
	DD	08H
	DD	015H
	DD	00H
	DD	0adH
	DD	02H
	DD	08H
	DD	016H
	DD	00H
	DD	0aeH
	DD	02H
	DD	08H
	DD	017H
	DD	00H
	DD	0afH
	DD	02H
	DD	08H
	DD	018H
	DD	02H
	DD	0b0H
	DD	02H
	DD	08H
	DD	01cH
	DD	01H
	DD	0b5H
	DD	02H
	DD	08H
	DD	01dH
	DD	00H
	DD	0b8H
	DD	02H
	DD	08H
	DD	01eH
	DD	01H
	DD	0b9H
	DD	02H
	DD	08H
	DD	01fH
	DD	00H
	DD	0bcH
	DD	02H
	DD	08H
	DD	020H
	DD	00H
	DD	0bdH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	080000009H
	DD	02H
	DD	02bH
	DD	08000000bH
	DD	02H
	DD	02bH
	DD	08000000dH
	DD	02H
	DD	02bH
	DD	06H
	DD	03H
	DD	06H
	DD	02H
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	02H
	DD	0aH
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	0aH
	DD	02H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	0aH
	DD	08000001aH
	DD	019H
	DD	01bH
	DD	02bH
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@xdynamics_gui@@UEBAPEBUQMetaObject@@XZ ; xdynamics_gui::metaObject
PUBLIC	?qt_metacast@xdynamics_gui@@UEAAPEAXPEBD@Z	; xdynamics_gui::qt_metacast
PUBLIC	?qt_metacall@xdynamics_gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xdynamics_gui::qt_metacall
PUBLIC	?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xdynamics_gui::qt_static_metacall
PUBLIC	?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B ; xdynamics_gui::staticMetaObject
EXTRN	atexit:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_glewInit:PROC
EXTRN	?xNew@xdynamics_gui@@AEAAXXZ:PROC		; xdynamics_gui::xNew
EXTRN	?xSave@xdynamics_gui@@AEAAXXZ:PROC		; xdynamics_gui::xSave
EXTRN	?xOpen@xdynamics_gui@@AEAAXXZ:PROC		; xdynamics_gui::xOpen
EXTRN	?xCylinder@xdynamics_gui@@AEAAXXZ:PROC		; xdynamics_gui::xCylinder
EXTRN	?xCube@xdynamics_gui@@AEAAXXZ:PROC		; xdynamics_gui::xCube
EXTRN	?xChart@xdynamics_gui@@AEAAXXZ:PROC		; xdynamics_gui::xChart
EXTRN	?xGetSimulationWidget@xdynamics_gui@@AEAAXPEAVwsimulation@@@Z:PROC ; xdynamics_gui::xGetSimulationWidget
EXTRN	?xGetPointMassWidget@xdynamics_gui@@AEAAXPEAVwpointmass@@@Z:PROC ; xdynamics_gui::xGetPointMassWidget
EXTRN	?xGetResultWidget@xdynamics_gui@@AEAAXPEAVwresult@@@Z:PROC ; xdynamics_gui::xGetResultWidget
EXTRN	?xRunSimulationThread@xdynamics_gui@@AEAAXNIN@Z:PROC ; xdynamics_gui::xRunSimulationThread
EXTRN	?xExitSimulationThread@xdynamics_gui@@AEAAXXZ:PROC ; xdynamics_gui::xExitSimulationThread
EXTRN	?xRecieveProgress@xdynamics_gui@@AEAAXHVQString@@@Z:PROC ; xdynamics_gui::xRecieveProgress
EXTRN	?xEditCommandLine@xdynamics_gui@@AEAAXXZ:PROC	; xdynamics_gui::xEditCommandLine
EXTRN	?xGeometrySelection@xdynamics_gui@@AEAAXVQString@@@Z:PROC ; xdynamics_gui::xGeometrySelection
EXTRN	?xReleaseOperation@xdynamics_gui@@AEAAXXZ:PROC	; xdynamics_gui::xReleaseOperation
EXTRN	?xInitializeWidgetStatement@xdynamics_gui@@AEAAXXZ:PROC ; xdynamics_gui::xInitializeWidgetStatement
EXTRN	?xOnGeometrySelectionOfPointMass@xdynamics_gui@@AEAAXXZ:PROC ; xdynamics_gui::xOnGeometrySelectionOfPointMass
EXTRN	?xStopSimulationThread@xdynamics_gui@@AEAAXXZ:PROC ; xdynamics_gui::xStopSimulationThread
EXTRN	?xReleaseResultCallThread@xdynamics_gui@@AEAAXXZ:PROC ; xdynamics_gui::xReleaseResultCallThread
EXTRN	?xContextMenuProcess@xdynamics_gui@@AEAAXVQString@@W4contextMenuType@@@Z:PROC ; xdynamics_gui::xContextMenuProcess
EXTRN	?xSetupResultNavigatorByChangeTargetCombo@xdynamics_gui@@AEAAXH@Z:PROC ; xdynamics_gui::xSetupResultNavigatorByChangeTargetCombo
EXTRN	?xUploadResultThisModel@xdynamics_gui@@AEAAXXZ:PROC ; xdynamics_gui::xUploadResultThisModel
EXTRN	?xSetupParticleBufferColorDistribution@xdynamics_gui@@AEAAXH@Z:PROC ; xdynamics_gui::xSetupParticleBufferColorDistribution
EXTRN	?xSelectStartPoint@xdynamics_gui@@AEAAXXZ:PROC	; xdynamics_gui::xSelectStartPoint
EXTRN	?xPassDistribution@xdynamics_gui@@AEAAXXZ:PROC	; xdynamics_gui::xPassDistribution
EXTRN	__ImageBase:BYTE
EXTRN	_fltused:DWORD
_BSS	SEGMENT
?g_vglew@@3VxvGlew@@A DB 01H DUP (?)			; g_vglew
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0xvGlew@@QEAA@XZ DD imagerel $LN4
	DD	imagerel $LN4+30
	DD	imagerel $unwind$??0xvGlew@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__Eg_vglew@@YAXXZ DD imagerel ??__Eg_vglew@@YAXXZ
	DD	imagerel ??__Eg_vglew@@YAXXZ+33
	DD	imagerel $unwind$??__Eg_vglew@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?qt_metacall@xdynamics_gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+112
	DD	imagerel $unwind$?qt_metacall@xdynamics_gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN39
	DD	imagerel $LN39+736
	DD	imagerel $unwind$?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
?g_vglew$initializer$@@3P6AXXZEA DQ FLAT:??__Eg_vglew@@YAXXZ ; g_vglew$initializer$
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B DB 8 DUP(00H) ; xdynamics_gui::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_xdynamics_gui@@3Uqt_meta_stringdata_xdynamics_gui_t@@B
	DQ	FLAT:?qt_meta_data_xdynamics_gui@@3QBIB
	DQ	FLAT:?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
_DATA	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 041201H
	DD	083412H
	DD	0700e5212H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?qt_metacall@xdynamics_gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 081401H
	DD	086414H
	DD	075414H
	DD	063414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__Eg_vglew@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0xvGlew@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xdynamics_gui@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xdynamics_gui@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__E?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xdynamics_gui::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xdynamics_gui.cpp
; Line 194
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B, rax
; Line 199
	ret	0
??__E?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xdynamics_gui::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
$T1 = 32
$T2 = 32
$T3 = 32
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xdynamics_gui::qt_static_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xdynamics_gui.cpp
; Line 158
$LN39:
; Line 159
	test	edx, edx
	jne	$LN36@qt_static_
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 48					; 00000030H
; Line 158
	mov	rdi, r9
	mov	rbx, rcx
; Line 162
	cmp	r8d, 24
	ja	$LN30@qt_static_
	lea	rcx, OFFSET FLAT:__ImageBase
	movsxd	rax, r8d
	mov	edx, DWORD PTR $LN35@qt_static_[rcx+rax*4]
	add	rdx, rcx
	jmp	rdx
$LN5@qt_static_:
; Line 163
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 163
	jmp	?xNew@xdynamics_gui@@AEAAXXZ		; xdynamics_gui::xNew
$LN6@qt_static_:
; Line 164
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 164
	jmp	?xSave@xdynamics_gui@@AEAAXXZ		; xdynamics_gui::xSave
$LN7@qt_static_:
; Line 165
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 165
	jmp	?xOpen@xdynamics_gui@@AEAAXXZ		; xdynamics_gui::xOpen
$LN8@qt_static_:
; Line 166
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 166
	jmp	?xCylinder@xdynamics_gui@@AEAAXXZ	; xdynamics_gui::xCylinder
$LN9@qt_static_:
; Line 167
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 167
	jmp	?xCube@xdynamics_gui@@AEAAXXZ		; xdynamics_gui::xCube
$LN10@qt_static_:
; Line 168
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 168
	jmp	?xChart@xdynamics_gui@@AEAAXXZ		; xdynamics_gui::xChart
$LN11@qt_static_:
; Line 169
	mov	rdx, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	rdx, QWORD PTR [rdx]
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 169
	jmp	?xGetSimulationWidget@xdynamics_gui@@AEAAXPEAVwsimulation@@@Z ; xdynamics_gui::xGetSimulationWidget
$LN12@qt_static_:
; Line 170
	mov	rdx, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	rdx, QWORD PTR [rdx]
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 170
	jmp	?xGetPointMassWidget@xdynamics_gui@@AEAAXPEAVwpointmass@@@Z ; xdynamics_gui::xGetPointMassWidget
$LN13@qt_static_:
; Line 171
	mov	rdx, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	rdx, QWORD PTR [rdx]
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 171
	jmp	?xGetResultWidget@xdynamics_gui@@AEAAXPEAVwresult@@@Z ; xdynamics_gui::xGetResultWidget
$LN14@qt_static_:
; Line 172
	mov	rcx, QWORD PTR [r9+16]
	mov	rax, QWORD PTR [r9+24]
	mov	rdx, QWORD PTR [r9+8]
	mov	r8d, DWORD PTR [rcx]
	mov	rcx, rbx
	movsd	xmm3, QWORD PTR [rax]
	movsd	xmm1, QWORD PTR [rdx]
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 172
	jmp	?xRunSimulationThread@xdynamics_gui@@AEAAXNIN@Z ; xdynamics_gui::xRunSimulationThread
$LN15@qt_static_:
; Line 173
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 173
	jmp	?xExitSimulationThread@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xExitSimulationThread
$LN16@qt_static_:
; Line 174
	mov	rdx, QWORD PTR [r9+16]
	lea	rcx, QWORD PTR $T3[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	rcx, QWORD PTR [rdi+8]
	mov	r8, rax
	mov	edx, DWORD PTR [rcx]
	mov	rcx, rbx
	call	?xRecieveProgress@xdynamics_gui@@AEAAXHVQString@@@Z ; xdynamics_gui::xRecieveProgress
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN17@qt_static_:
; Line 175
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 175
	jmp	?xEditCommandLine@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xEditCommandLine
$LN18@qt_static_:
; Line 176
	mov	rdx, QWORD PTR [r9+8]
	lea	rcx, QWORD PTR $T2[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	rdx, rax
	mov	rcx, rbx
	call	?xGeometrySelection@xdynamics_gui@@AEAAXVQString@@@Z ; xdynamics_gui::xGeometrySelection
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN19@qt_static_:
; Line 177
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 177
	jmp	?xReleaseOperation@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xReleaseOperation
$LN20@qt_static_:
; Line 178
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 178
	jmp	?xInitializeWidgetStatement@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xInitializeWidgetStatement
$LN21@qt_static_:
; Line 179
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 179
	jmp	?xOnGeometrySelectionOfPointMass@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xOnGeometrySelectionOfPointMass
$LN22@qt_static_:
; Line 180
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 180
	jmp	?xStopSimulationThread@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xStopSimulationThread
$LN23@qt_static_:
; Line 181
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 181
	jmp	?xReleaseResultCallThread@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xReleaseResultCallThread
$LN24@qt_static_:
; Line 182
	mov	rdx, QWORD PTR [r9+8]
	lea	rcx, QWORD PTR $T1[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	rcx, QWORD PTR [rdi+16]
	mov	rdx, rax
	mov	r8d, DWORD PTR [rcx]
	mov	rcx, rbx
	call	?xContextMenuProcess@xdynamics_gui@@AEAAXVQString@@W4contextMenuType@@@Z ; xdynamics_gui::xContextMenuProcess
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN25@qt_static_:
; Line 183
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 183
	jmp	?xSetupResultNavigatorByChangeTargetCombo@xdynamics_gui@@AEAAXH@Z ; xdynamics_gui::xSetupResultNavigatorByChangeTargetCombo
$LN26@qt_static_:
; Line 184
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 184
	jmp	?xUploadResultThisModel@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xUploadResultThisModel
$LN27@qt_static_:
; Line 185
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 185
	jmp	?xSetupParticleBufferColorDistribution@xdynamics_gui@@AEAAXH@Z ; xdynamics_gui::xSetupParticleBufferColorDistribution
$LN28@qt_static_:
; Line 186
	mov	rcx, rbx
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 186
	jmp	?xSelectStartPoint@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xSelectStartPoint
$LN29@qt_static_:
; Line 187
	mov	rcx, rbx
	call	?xPassDistribution@xdynamics_gui@@AEAAXXZ ; xdynamics_gui::xPassDistribution
$LN30@qt_static_:
; Line 191
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
$LN36@qt_static_:
	ret	0
	npad	3
$LN35@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
	DD	$LN17@qt_static_
	DD	$LN18@qt_static_
	DD	$LN19@qt_static_
	DD	$LN20@qt_static_
	DD	$LN21@qt_static_
	DD	$LN22@qt_static_
	DD	$LN23@qt_static_
	DD	$LN24@qt_static_
	DD	$LN25@qt_static_
	DD	$LN26@qt_static_
	DD	$LN27@qt_static_
	DD	$LN28@qt_static_
	DD	$LN29@qt_static_
?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xdynamics_gui::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacall@xdynamics_gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xdynamics_gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xdynamics_gui::qt_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xdynamics_gui.cpp
; Line 217
$LN10:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rsi, r9
	mov	edi, edx
	mov	rbp, rcx
; Line 218
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	ebx, eax
; Line 219
	test	eax, eax
	js	SHORT $LN1@qt_metacal
; Line 221
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 222
	cmp	eax, 25
	jge	SHORT $LN7@qt_metacal
; Line 223
	mov	r9, rsi
	mov	r8d, eax
	xor	edx, edx
	mov	rcx, rbp
	call	?qt_static_metacall@xdynamics_gui@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xdynamics_gui::qt_static_metacall
; Line 224
	jmp	SHORT $LN7@qt_metacal
$LN3@qt_metacal:
; Line 225
	cmp	edi, 12
	jne	SHORT $LN6@qt_metacal
; Line 226
	cmp	ebx, 25
	jge	SHORT $LN7@qt_metacal
; Line 227
	mov	rax, QWORD PTR [rsi]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 230
	sub	ebx, 25
$LN6@qt_metacal:
	mov	eax, ebx
$LN1@qt_metacal:
; Line 231
	mov	rbx, QWORD PTR [rsp+48]
	mov	rbp, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?qt_metacall@xdynamics_gui@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xdynamics_gui::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacast@xdynamics_gui@@UEAAPEAXPEBD@Z
_TEXT	SEGMENT
this$ = 8
_clname$ = 16
?qt_metacast@xdynamics_gui@@UEAAPEAXPEBD@Z PROC		; xdynamics_gui::qt_metacast, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xdynamics_gui.cpp
; Line 209
	mov	r9, rdx
	mov	r10, rcx
; Line 210
	test	rdx, rdx
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
; Line 214
	ret	0
$LN2@qt_metacas:
; Line 211
	lea	r8, OFFSET FLAT:?qt_meta_stringdata_xdynamics_gui@@3Uqt_meta_stringdata_xdynamics_gui_t@@B+792
	mov	rax, r9
	sub	r8, r9
	npad	5
$LL5@qt_metacas:
	movzx	edx, BYTE PTR [rax]
	movzx	ecx, BYTE PTR [rax+r8]
	sub	edx, ecx
	jne	SHORT $LN6@qt_metacas
	inc	rax
	test	ecx, ecx
	jne	SHORT $LL5@qt_metacas
$LN6@qt_metacas:
	test	edx, edx
	jne	SHORT $LN3@qt_metacas
; Line 212
	mov	rax, r10
; Line 214
	ret	0
$LN3@qt_metacas:
; Line 213
	mov	rdx, r9
	mov	rcx, r10
	rex_jmp	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
?qt_metacast@xdynamics_gui@@UEAAPEAXPEBD@Z ENDP		; xdynamics_gui::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?metaObject@xdynamics_gui@@UEBAPEBUQMetaObject@@XZ
_TEXT	SEGMENT
this$ = 8
?metaObject@xdynamics_gui@@UEBAPEBUQMetaObject@@XZ PROC	; xdynamics_gui::metaObject, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xdynamics_gui.cpp
; Line 205
	mov	rcx, QWORD PTR [rcx+8]
	cmp	QWORD PTR [rcx+40], 0
	je	SHORT $LN3@metaObject
	rex_jmp	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xdynamics_gui@@2UQMetaObject@@B ; xdynamics_gui::staticMetaObject
; Line 206
	ret	0
?metaObject@xdynamics_gui@@UEBAPEBUQMetaObject@@XZ ENDP	; xdynamics_gui::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Fg_vglew@@YAXXZ
text$yd	SEGMENT
??__Fg_vglew@@YAXXZ PROC				; `dynamic atexit destructor for 'g_vglew'', COMDAT
	ret	0
??__Fg_vglew@@YAXXZ ENDP				; `dynamic atexit destructor for 'g_vglew''
text$yd	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Eg_vglew@@YAXXZ
text$di	SEGMENT
??__Eg_vglew@@YAXXZ PROC				; `dynamic initializer for 'g_vglew'', COMDAT
; File c:\xdynamics\include\xdynamics_gui\xvglew.h
; Line 44
	sub	rsp, 40					; 00000028H
; Line 20
	call	QWORD PTR __imp_glewInit
; Line 44
	lea	rcx, OFFSET FLAT:??__Fg_vglew@@YAXXZ	; `dynamic atexit destructor for 'g_vglew''
; Line 21
	mov	BYTE PTR ?g_vglew@@3VxvGlew@@A, 1
; Line 44
	add	rsp, 40					; 00000028H
	jmp	atexit
??__Eg_vglew@@YAXXZ ENDP				; `dynamic initializer for 'g_vglew''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1xvGlew@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1xvGlew@@QEAA@XZ PROC					; xvGlew::~xvGlew, COMDAT
; File c:\xdynamics\include\xdynamics_gui\xvglew.h
; Line 30
	ret	0
??1xvGlew@@QEAA@XZ ENDP					; xvGlew::~xvGlew
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0xvGlew@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??0xvGlew@@QEAA@XZ PROC					; xvGlew::xvGlew, COMDAT
; File c:\xdynamics\include\xdynamics_gui\xvglew.h
; Line 19
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	BYTE PTR [rcx], 0
; Line 20
	call	QWORD PTR __imp_glewInit
; Line 22
	mov	rax, rbx
	mov	BYTE PTR [rbx], 1
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0xvGlew@@QEAA@XZ ENDP					; xvGlew::xvGlew
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 118
	mov	rax, QWORD PTR [rcx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
