; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QGLWidget@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_xGLWidget@@3Uqt_meta_stringdata_xGLWidget_t@@B DD 0ffffffffH ; qt_meta_stringdata_xGLWidget
	DD	09H
	DD	00H
	ORG $+4
	DQ	00000000000001e0H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	00000000000001d2H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000001cbH
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	00000000000001b4H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	00000000000001a2H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000019bH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000194H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	0000000000000192H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000192H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	000000000000018bH
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	0000000000000181H
	DD	0ffffffffH
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000179H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000169H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	000000000000015eH
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000153H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	0000000000000148H
	DD	0ffffffffH
	DD	03H
	DD	00H
	ORG $+4
	DQ	0000000000000140H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	000000000000012cH
	DD	0ffffffffH
	DD	024H
	DD	00H
	ORG $+4
	DQ	0000000000000123H
	DD	0ffffffffH
	DD	01H
	DD	00H
	ORG $+4
	DQ	0000000000000130H
	DB	078H
	DB	047H
	DB	04cH
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	00H
	DB	078H
	DB	052H
	DB	06fH
	DB	074H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	061H
	DB	06eH
	DB	067H
	DB	06cH
	DB	065H
	DB	00H
	DB	079H
	DB	052H
	DB	06fH
	DB	074H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	07aH
	DB	052H
	DB	06fH
	DB	074H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	063H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	041H
	DB	06eH
	DB	069H
	DB	06dH
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	046H
	DB	072H
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	047H
	DB	065H
	DB	06fH
	DB	06dH
	DB	065H
	DB	074H
	DB	072H
	DB	079H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	072H
	DB	065H
	DB	06cH
	DB	065H
	DB	061H
	DB	073H
	DB	065H
	DB	04fH
	DB	070H
	DB	065H
	DB	072H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	063H
	DB	06fH
	DB	06eH
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	053H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	00H
	DB	063H
	DB	06fH
	DB	06eH
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	04dH
	DB	065H
	DB	06eH
	DB	075H
	DB	054H
	DB	079H
	DB	070H
	DB	065H
	DB	00H
	DB	066H
	DB	069H
	DB	074H
	DB	056H
	DB	069H
	DB	065H
	DB	077H
	DB	00H
	DB	073H
	DB	065H
	DB	074H
	DB	058H
	DB	052H
	DB	06fH
	DB	074H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	073H
	DB	065H
	DB	074H
	DB	059H
	DB	052H
	DB	06fH
	DB	074H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	073H
	DB	065H
	DB	074H
	DB	05aH
	DB	052H
	DB	06fH
	DB	074H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	053H
	DB	068H
	DB	06fH
	DB	077H
	DB	043H
	DB	06fH
	DB	06eH
	DB	074H
	DB	065H
	DB	078H
	DB	074H
	DB	04dH
	DB	065H
	DB	06eH
	DB	075H
	DB	00H
	DB	070H
	DB	06fH
	DB	073H
	DB	00H
	DB	073H
	DB	065H
	DB	074H
	DB	053H
	DB	06bH
	DB	065H
	DB	074H
	DB	063H
	DB	068H
	DB	053H
	DB	070H
	DB	061H
	DB	063H
	DB	065H
	DB	00H
	DB	073H
	DB	065H
	DB	074H
	DB	075H
	DB	070H
	DB	050H
	DB	061H
	DB	072H
	DB	074H
	DB	069H
	DB	063H
	DB	06cH
	DB	065H
	DB	042H
	DB	075H
	DB	066H
	DB	066H
	DB	065H
	DB	072H
	DB	043H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	044H
	DB	069H
	DB	073H
	DB	074H
	DB	072H
	DB	069H
	DB	062H
	DB	075H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	06eH
	DB	00H
	ORG $+6
?qt_meta_data_xGLWidget@@3QBIB DD 08H			; qt_meta_data_xGLWidget
	DD	00H
	DD	00H
	DD	00H
	DD	0fH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	07H
	DD	01H
	DD	01H
	DD	059H
	DD	02H
	DD	06H
	DD	04H
	DD	01H
	DD	05cH
	DD	02H
	DD	06H
	DD	05H
	DD	01H
	DD	05fH
	DD	02H
	DD	06H
	DD	06H
	DD	00H
	DD	062H
	DD	02H
	DD	06H
	DD	07H
	DD	01H
	DD	063H
	DD	02H
	DD	06H
	DD	08H
	DD	00H
	DD	066H
	DD	02H
	DD	06H
	DD	09H
	DD	02H
	DD	067H
	DD	02H
	DD	06H
	DD	0bH
	DD	00H
	DD	06cH
	DD	02H
	DD	0aH
	DD	0cH
	DD	01H
	DD	06dH
	DD	02H
	DD	0aH
	DD	0dH
	DD	01H
	DD	070H
	DD	02H
	DD	0aH
	DD	0eH
	DD	01H
	DD	073H
	DD	02H
	DD	0aH
	DD	0fH
	DD	01H
	DD	076H
	DD	02H
	DD	0aH
	DD	011H
	DD	00H
	DD	079H
	DD	02H
	DD	0aH
	DD	012H
	DD	01H
	DD	07aH
	DD	02H
	DD	0aH
	DD	012H
	DD	00H
	DD	07dH
	DD	02H
	DD	02aH
	DD	02bH
	DD	02H
	DD	03H
	DD	02bH
	DD	02H
	DD	03H
	DD	02bH
	DD	02H
	DD	03H
	DD	02bH
	DD	02bH
	DD	0aH
	DD	02H
	DD	02bH
	DD	02bH
	DD	0aH
	DD	08000000aH
	DD	02H
	DD	02H
	DD	02bH
	DD	02bH
	DD	02H
	DD	03H
	DD	02bH
	DD	02H
	DD	03H
	DD	02bH
	DD	02H
	DD	03H
	DD	02bH
	DD	019H
	DD	010H
	DD	02bH
	DD	02bH
	DD	02H
	DD	013H
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@xGLWidget@@UEBAPEBUQMetaObject@@XZ	; xGLWidget::metaObject
PUBLIC	?qt_metacast@xGLWidget@@UEAAPEAXPEBD@Z		; xGLWidget::qt_metacast
PUBLIC	?qt_metacall@xGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; xGLWidget::qt_metacall
PUBLIC	?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xGLWidget::qt_static_metacall
PUBLIC	?xRotationChanged@xGLWidget@@QEAAXH@Z		; xGLWidget::xRotationChanged
PUBLIC	?yRotationChanged@xGLWidget@@QEAAXH@Z		; xGLWidget::yRotationChanged
PUBLIC	?zRotationChanged@xGLWidget@@QEAAXH@Z		; xGLWidget::zRotationChanged
PUBLIC	?changedAnimationFrame@xGLWidget@@QEAAXXZ	; xGLWidget::changedAnimationFrame
PUBLIC	?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z ; xGLWidget::signalGeometrySelection
PUBLIC	?releaseOperation@xGLWidget@@QEAAXXZ		; xGLWidget::releaseOperation
PUBLIC	?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z ; xGLWidget::contextSignal
PUBLIC	?staticMetaObject@xGLWidget@@2UQMetaObject@@B	; xGLWidget::staticMetaObject
EXTRN	atexit:PROC
EXTRN	__imp_glewInit:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_??0QString@@QEAA@AEBV0@@Z:PROC
EXTRN	__imp_??1QString@@QEAA@XZ:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QGLWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?fitView@xGLWidget@@QEAAXXZ:PROC		; xGLWidget::fitView
EXTRN	?setXRotation@xGLWidget@@QEAAXH@Z:PROC		; xGLWidget::setXRotation
EXTRN	?setYRotation@xGLWidget@@QEAAXH@Z:PROC		; xGLWidget::setYRotation
EXTRN	?setZRotation@xGLWidget@@QEAAXH@Z:PROC		; xGLWidget::setZRotation
EXTRN	?ShowContextMenu@xGLWidget@@QEAAXAEBVQPoint@@@Z:PROC ; xGLWidget::ShowContextMenu
EXTRN	?setSketchSpace@xGLWidget@@QEAAXXZ:PROC		; xGLWidget::setSketchSpace
EXTRN	?setupParticleBufferColorDistribution@xGLWidget@@QEAAXH@Z:PROC ; xGLWidget::setupParticleBufferColorDistribution
EXTRN	__CxxFrameHandler3:PROC
EXTRN	__GSHandlerCheck_EH:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__ImageBase:BYTE
EXTRN	__security_cookie:QWORD
_BSS	SEGMENT
?g_vglew@@3VxvGlew@@A DB 01H DUP (?)			; g_vglew
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0xvGlew@@QEAA@XZ DD imagerel $LN4
	DD	imagerel $LN4+30
	DD	imagerel $unwind$??0xvGlew@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__Eg_vglew@@YAXXZ DD imagerel ??__Eg_vglew@@YAXXZ
	DD	imagerel ??__Eg_vglew@@YAXXZ+33
	DD	imagerel $unwind$??__Eg_vglew@@YAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?qt_metacall@xGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+112
	DD	imagerel $unwind$?qt_metacall@xGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN86
	DD	imagerel $LN86+792
	DD	imagerel $unwind$?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?xRotationChanged@xGLWidget@@QEAAXH@Z DD imagerel $LN4
	DD	imagerel $LN4+53
	DD	imagerel $unwind$?xRotationChanged@xGLWidget@@QEAAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?yRotationChanged@xGLWidget@@QEAAXH@Z DD imagerel $LN4
	DD	imagerel $LN4+56
	DD	imagerel $unwind$?yRotationChanged@xGLWidget@@QEAAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?zRotationChanged@xGLWidget@@QEAAXH@Z DD imagerel $LN4
	DD	imagerel $LN4+56
	DD	imagerel $unwind$?zRotationChanged@xGLWidget@@QEAAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z DD imagerel $LN6
	DD	imagerel $LN6+76
	DD	imagerel $unwind$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z DD imagerel $LN6
	DD	imagerel $LN6+114
	DD	imagerel $unwind$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z
pdata	ENDS
CRT$XCU	SEGMENT
?g_vglew$initializer$@@3P6AXXZEA DQ FLAT:??__Eg_vglew@@YAXXZ ; g_vglew$initializer$
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@xGLWidget@@2UQMetaObject@@B DB 8 DUP(00H) ; xGLWidget::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_xGLWidget@@3Uqt_meta_stringdata_xGLWidget_t@@B
	DQ	FLAT:?qt_meta_data_xGLWidget@@3QBIB
	DQ	FLAT:?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
_DATA	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z DD imagerel ?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z+79
	DD	00H
	DD	imagerel ?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z+103
	DD	0ffffffffH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z@4HA
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z
	DD	00H
	DD	00H
	DD	02H
	DD	imagerel $ip2state$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z
	DD	028H
	DD	00H
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z DD 021f19H
	DD	03004b208H
	DD	imagerel __GSHandlerCheck_EH
	DD	imagerel $cppxdata$?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z
	DD	052H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z DD imagerel ?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z+54
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0??signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z@4HA
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z
	DD	00H
	DD	00H
	DD	01H
	DD	imagerel $ip2state$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z
	DD	020H
	DD	00H
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z DD 021311H
	DD	03006720aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?zRotationChanged@xGLWidget@@QEAAXH@Z DD 010801H
	DD	06208H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?yRotationChanged@xGLWidget@@QEAAXH@Z DD 010801H
	DD	06208H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?xRotationChanged@xGLWidget@@QEAAXH@Z DD 010801H
	DD	06208H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 040a01H
	DD	08340aH
	DD	07006520aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?qt_metacall@xGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 081401H
	DD	086414H
	DD	075414H
	DD	063414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__Eg_vglew@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0xvGlew@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@xGLWidget@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@xGLWidget@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@xGLWidget@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__E?staticMetaObject@xGLWidget@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@xGLWidget@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'xGLWidget::staticMetaObject'', COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 200
	mov	rax, QWORD PTR __imp_?staticMetaObject@QGLWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@xGLWidget@@2UQMetaObject@@B, rax
; Line 205
	ret	0
??__E?staticMetaObject@xGLWidget@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'xGLWidget::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z
_TEXT	SEGMENT
_t1$GSCopy$ = 48
__$ArrayPad$ = 80
this$ = 112
_t1$ = 120
_t2$ = 128
?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z PROC ; xGLWidget::contextSignal, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 281
$LN6:
	mov	r11, rsp
	push	rbx
	sub	rsp, 96					; 00000060H
	mov	QWORD PTR [r11-64], -2
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
	mov	rbx, rdx
	mov	QWORD PTR [r11-56], rdx
	mov	DWORD PTR [r11-72], r8d
; Line 282
	mov	QWORD PTR [r11-48], 0
	mov	QWORD PTR [r11-40], rdx
	lea	rax, QWORD PTR [r11-72]
	mov	QWORD PTR [r11-32], rax
; Line 283
	lea	r9, QWORD PTR [r11-48]
	mov	r8d, 6
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
	npad	1
; Line 284
	mov	rcx, rbx
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	add	rsp, 96					; 00000060H
	pop	rbx
	ret	0
?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z ENDP ; xGLWidget::contextSignal
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
_t1$GSCopy$ = 48
__$ArrayPad$ = 80
this$ = 112
_t1$ = 120
_t2$ = 128
?dtor$0@?0??contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z@4HA PROC ; `xGLWidget::contextSignal'::`1'::dtor$0
	mov	rcx, QWORD PTR _t1$GSCopy$[rdx]
	rex_jmp	QWORD PTR __imp_??1QString@@QEAA@XZ
?dtor$0@?0??contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z@4HA ENDP ; `xGLWidget::contextSignal'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT text$x
text$x	SEGMENT
_t1$GSCopy$ = 48
__$ArrayPad$ = 80
this$ = 112
_t1$ = 120
_t2$ = 128
?dtor$0@?0??contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z@4HA PROC ; `xGLWidget::contextSignal'::`1'::dtor$0
	mov	rcx, QWORD PTR _t1$GSCopy$[rdx]
	rex_jmp	QWORD PTR __imp_??1QString@@QEAA@XZ
?dtor$0@?0??contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z@4HA ENDP ; `xGLWidget::contextSignal'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?releaseOperation@xGLWidget@@QEAAXXZ
_TEXT	SEGMENT
this$ = 8
?releaseOperation@xGLWidget@@QEAAXXZ PROC		; xGLWidget::releaseOperation, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 276
	xor	r9d, r9d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	lea	r8d, QWORD PTR [r9+5]
	rex_jmp	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
?releaseOperation@xGLWidget@@QEAAXXZ ENDP		; xGLWidget::releaseOperation
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z
_TEXT	SEGMENT
$T1 = 32
_a$ = 40
this$ = 80
_t1$ = 88
?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z PROC ; xGLWidget::signalGeometrySelection, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 268
$LN6:
	mov	QWORD PTR [rsp+16], rdx
	push	rbx
	sub	rsp, 64					; 00000040H
	mov	QWORD PTR $T1[rsp], -2
	mov	rbx, rdx
; Line 269
	mov	QWORD PTR _a$[rsp], 0
	mov	QWORD PTR _a$[rsp+8], rdx
; Line 270
	lea	r9, QWORD PTR _a$[rsp]
	mov	r8d, 4
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
	npad	1
; Line 271
	mov	rcx, rbx
	call	QWORD PTR __imp_??1QString@@QEAA@XZ
	add	rsp, 64					; 00000040H
	pop	rbx
	ret	0
?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z ENDP ; xGLWidget::signalGeometrySelection
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
$T1 = 32
_a$ = 40
this$ = 80
_t1$ = 88
?dtor$0@?0??signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z@4HA PROC ; `xGLWidget::signalGeometrySelection'::`1'::dtor$0
	mov	rcx, QWORD PTR _t1$[rdx]
	rex_jmp	QWORD PTR __imp_??1QString@@QEAA@XZ
?dtor$0@?0??signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z@4HA ENDP ; `xGLWidget::signalGeometrySelection'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT text$x
text$x	SEGMENT
$T1 = 32
_a$ = 40
this$ = 80
_t1$ = 88
?dtor$0@?0??signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z@4HA PROC ; `xGLWidget::signalGeometrySelection'::`1'::dtor$0
	mov	rcx, QWORD PTR _t1$[rdx]
	rex_jmp	QWORD PTR __imp_??1QString@@QEAA@XZ
?dtor$0@?0??signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z@4HA ENDP ; `xGLWidget::signalGeometrySelection'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?changedAnimationFrame@xGLWidget@@QEAAXXZ
_TEXT	SEGMENT
this$ = 8
?changedAnimationFrame@xGLWidget@@QEAAXXZ PROC		; xGLWidget::changedAnimationFrame, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 263
	xor	r9d, r9d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	lea	r8d, QWORD PTR [r9+3]
	rex_jmp	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
?changedAnimationFrame@xGLWidget@@QEAAXXZ ENDP		; xGLWidget::changedAnimationFrame
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?zRotationChanged@xGLWidget@@QEAAXH@Z
_TEXT	SEGMENT
_a$ = 32
this$ = 64
_t1$ = 72
?zRotationChanged@xGLWidget@@QEAAXH@Z PROC		; xGLWidget::zRotationChanged, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 255
$LN4:
	mov	DWORD PTR [rsp+16], edx
	sub	rsp, 56					; 00000038H
; Line 256
	lea	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp], 0
; Line 257
	lea	r9, QWORD PTR _a$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	mov	r8d, 2
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 258
	add	rsp, 56					; 00000038H
	ret	0
?zRotationChanged@xGLWidget@@QEAAXH@Z ENDP		; xGLWidget::zRotationChanged
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?yRotationChanged@xGLWidget@@QEAAXH@Z
_TEXT	SEGMENT
_a$ = 32
this$ = 64
_t1$ = 72
?yRotationChanged@xGLWidget@@QEAAXH@Z PROC		; xGLWidget::yRotationChanged, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 248
$LN4:
	mov	DWORD PTR [rsp+16], edx
	sub	rsp, 56					; 00000038H
; Line 249
	lea	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp], 0
; Line 250
	lea	r9, QWORD PTR _a$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	mov	r8d, 1
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 251
	add	rsp, 56					; 00000038H
	ret	0
?yRotationChanged@xGLWidget@@QEAAXH@Z ENDP		; xGLWidget::yRotationChanged
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?xRotationChanged@xGLWidget@@QEAAXH@Z
_TEXT	SEGMENT
_a$ = 32
this$ = 64
_t1$ = 72
?xRotationChanged@xGLWidget@@QEAAXH@Z PROC		; xGLWidget::xRotationChanged, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 241
$LN4:
	mov	DWORD PTR [rsp+16], edx
	sub	rsp, 56					; 00000038H
; Line 242
	lea	rax, QWORD PTR _t1$[rsp]
	mov	QWORD PTR _a$[rsp], 0
; Line 243
	lea	r9, QWORD PTR _a$[rsp]
	mov	QWORD PTR _a$[rsp+8], rax
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 244
	add	rsp, 56					; 00000038H
	ret	0
?xRotationChanged@xGLWidget@@QEAAXH@Z ENDP		; xGLWidget::xRotationChanged
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
$T1 = 32
$T2 = 32
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; xGLWidget::qt_static_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 123
$LN86:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, r9
	mov	rbx, rcx
; Line 124
	test	edx, edx
	jne	$LN4@qt_static_
; Line 127
	cmp	r8d, 14
	ja	$LN29@qt_static_
	lea	rcx, OFFSET FLAT:__ImageBase
	movsxd	rax, r8d
	mov	edx, DWORD PTR $LN81@qt_static_[rcx+rax*4]
	add	rdx, rcx
	jmp	rdx
$LN6@qt_static_:
; Line 128
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 128
	jmp	?xRotationChanged@xGLWidget@@QEAAXH@Z	; xGLWidget::xRotationChanged
$LN7@qt_static_:
; Line 129
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 129
	jmp	?yRotationChanged@xGLWidget@@QEAAXH@Z	; xGLWidget::yRotationChanged
$LN8@qt_static_:
; Line 130
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 130
	jmp	?zRotationChanged@xGLWidget@@QEAAXH@Z	; xGLWidget::zRotationChanged
$LN9@qt_static_:
; Line 263
	mov	r8d, 3
$LN83@qt_static_:
; Line 197
	xor	r9d, r9d
	lea	rdx, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
	mov	rcx, rbx
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	rex_jmp	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
$LN10@qt_static_:
; Line 132
	mov	rdx, QWORD PTR [r9+8]
	lea	rcx, QWORD PTR $T2[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	rdx, rax
	mov	rcx, rbx
	call	?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z ; xGLWidget::signalGeometrySelection
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN11@qt_static_:
; Line 276
	mov	r8d, 5
; Line 133
	jmp	SHORT $LN83@qt_static_
$LN12@qt_static_:
; Line 134
	mov	rdx, QWORD PTR [r9+8]
	lea	rcx, QWORD PTR $T1[rsp]
	call	QWORD PTR __imp_??0QString@@QEAA@AEBV0@@Z
	mov	rcx, QWORD PTR [rdi+16]
	mov	rdx, rax
	mov	r8d, DWORD PTR [rcx]
	mov	rcx, rbx
	call	?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z ; xGLWidget::contextSignal
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN13@qt_static_:
; Line 135
	mov	rcx, rbx
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 135
	jmp	?fitView@xGLWidget@@QEAAXXZ		; xGLWidget::fitView
$LN14@qt_static_:
; Line 136
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 136
	jmp	?setXRotation@xGLWidget@@QEAAXH@Z	; xGLWidget::setXRotation
$LN15@qt_static_:
; Line 137
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 137
	jmp	?setYRotation@xGLWidget@@QEAAXH@Z	; xGLWidget::setYRotation
$LN16@qt_static_:
; Line 138
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 138
	jmp	?setZRotation@xGLWidget@@QEAAXH@Z	; xGLWidget::setZRotation
$LN17@qt_static_:
; Line 139
	mov	rdx, QWORD PTR [r9+8]
	mov	rcx, rbx
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 139
	jmp	?ShowContextMenu@xGLWidget@@QEAAXAEBVQPoint@@@Z ; xGLWidget::ShowContextMenu
$LN18@qt_static_:
; Line 140
	mov	rcx, rbx
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 140
	jmp	?setSketchSpace@xGLWidget@@QEAAXXZ	; xGLWidget::setSketchSpace
$LN19@qt_static_:
; Line 141
	mov	rax, QWORD PTR [r9+8]
	mov	rcx, rbx
	mov	edx, DWORD PTR [rax]
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 141
	jmp	?setupParticleBufferColorDistribution@xGLWidget@@QEAAXH@Z ; xGLWidget::setupParticleBufferColorDistribution
$LN20@qt_static_:
; Line 142
	mov	edx, -1
	mov	rcx, rbx
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 142
	jmp	?setupParticleBufferColorDistribution@xGLWidget@@QEAAXH@Z ; xGLWidget::setupParticleBufferColorDistribution
$LN4@qt_static_:
; Line 145
	cmp	edx, 10
	jne	$LN29@qt_static_
; Line 149
	mov	rcx, QWORD PTR [r9+8]
	lea	r8, OFFSET FLAT:?xRotationChanged@xGLWidget@@QEAAXH@Z ; xGLWidget::xRotationChanged
	mov	rdx, QWORD PTR [r9]
	mov	rax, QWORD PTR [rcx]
	cmp	rax, r8
	jne	SHORT $LN23@qt_static_
	test	rax, rax
	je	SHORT $LN68@qt_static_
	cmp	DWORD PTR [rcx+8], 0
	jne	SHORT $LN23@qt_static_
$LN68@qt_static_:
; Line 150
	mov	DWORD PTR [rdx], 0
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN23@qt_static_:
; Line 156
	lea	r8, OFFSET FLAT:?yRotationChanged@xGLWidget@@QEAAXH@Z ; xGLWidget::yRotationChanged
	cmp	rax, r8
	jne	SHORT $LN24@qt_static_
	test	rax, rax
	je	SHORT $LN69@qt_static_
	cmp	DWORD PTR [rcx+8], 0
	jne	SHORT $LN24@qt_static_
$LN69@qt_static_:
; Line 157
	mov	DWORD PTR [rdx], 1
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN24@qt_static_:
; Line 163
	lea	r8, OFFSET FLAT:?zRotationChanged@xGLWidget@@QEAAXH@Z ; xGLWidget::zRotationChanged
	cmp	rax, r8
	jne	SHORT $LN25@qt_static_
	test	rax, rax
	je	SHORT $LN70@qt_static_
	cmp	DWORD PTR [rcx+8], 0
	jne	SHORT $LN25@qt_static_
$LN70@qt_static_:
; Line 164
	mov	DWORD PTR [rdx], 2
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN25@qt_static_:
; Line 170
	lea	r8, OFFSET FLAT:?changedAnimationFrame@xGLWidget@@QEAAXXZ ; xGLWidget::changedAnimationFrame
	cmp	rax, r8
	jne	SHORT $LN26@qt_static_
	test	rax, rax
	je	SHORT $LN71@qt_static_
	cmp	DWORD PTR [rcx+8], 0
	jne	SHORT $LN26@qt_static_
$LN71@qt_static_:
; Line 171
	mov	DWORD PTR [rdx], 3
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN26@qt_static_:
; Line 177
	lea	r8, OFFSET FLAT:?signalGeometrySelection@xGLWidget@@QEAAXVQString@@@Z ; xGLWidget::signalGeometrySelection
	cmp	rax, r8
	jne	SHORT $LN27@qt_static_
	test	rax, rax
	je	SHORT $LN72@qt_static_
	cmp	DWORD PTR [rcx+8], 0
	jne	SHORT $LN27@qt_static_
$LN72@qt_static_:
; Line 178
	mov	DWORD PTR [rdx], 4
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN27@qt_static_:
; Line 184
	lea	r8, OFFSET FLAT:?releaseOperation@xGLWidget@@QEAAXXZ ; xGLWidget::releaseOperation
	cmp	rax, r8
	jne	SHORT $LN28@qt_static_
	test	rax, rax
	je	SHORT $LN73@qt_static_
	cmp	DWORD PTR [rcx+8], 0
	jne	SHORT $LN28@qt_static_
$LN73@qt_static_:
; Line 185
	mov	DWORD PTR [rdx], 5
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
$LN28@qt_static_:
; Line 191
	lea	r8, OFFSET FLAT:?contextSignal@xGLWidget@@QEAAXVQString@@W4contextMenuType@@@Z ; xGLWidget::contextSignal
	cmp	rax, r8
	jne	SHORT $LN29@qt_static_
	test	rax, rax
	je	SHORT $LN74@qt_static_
	cmp	DWORD PTR [rcx+8], 0
	jne	SHORT $LN29@qt_static_
$LN74@qt_static_:
; Line 192
	mov	DWORD PTR [rdx], 6
$LN29@qt_static_:
; Line 197
	mov	rbx, QWORD PTR [rsp+64]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
	npad	3
$LN81@qt_static_:
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
	DD	$LN17@qt_static_
	DD	$LN18@qt_static_
	DD	$LN19@qt_static_
	DD	$LN20@qt_static_
?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xGLWidget::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacall@xGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@xGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; xGLWidget::qt_metacall, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 223
$LN10:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rsi, r9
	mov	edi, edx
	mov	rbp, rcx
; Line 224
	call	QWORD PTR __imp_?qt_metacall@QGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	ebx, eax
; Line 225
	test	eax, eax
	js	SHORT $LN1@qt_metacal
; Line 227
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 228
	cmp	eax, 15
	jge	SHORT $LN7@qt_metacal
; Line 229
	mov	r9, rsi
	mov	r8d, eax
	xor	edx, edx
	mov	rcx, rbp
	call	?qt_static_metacall@xGLWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; xGLWidget::qt_static_metacall
; Line 230
	jmp	SHORT $LN7@qt_metacal
$LN3@qt_metacal:
; Line 231
	cmp	edi, 12
	jne	SHORT $LN6@qt_metacal
; Line 232
	cmp	ebx, 15
	jge	SHORT $LN7@qt_metacal
; Line 233
	mov	rax, QWORD PTR [rsi]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 236
	sub	ebx, 15
$LN6@qt_metacal:
	mov	eax, ebx
$LN1@qt_metacal:
; Line 237
	mov	rbx, QWORD PTR [rsp+48]
	mov	rbp, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?qt_metacall@xGLWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; xGLWidget::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qt_metacast@xGLWidget@@UEAAPEAXPEBD@Z
_TEXT	SEGMENT
this$ = 8
_clname$ = 16
?qt_metacast@xGLWidget@@UEAAPEAXPEBD@Z PROC		; xGLWidget::qt_metacast, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 215
	mov	r9, rdx
	mov	r10, rcx
; Line 216
	test	rdx, rdx
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
; Line 220
	ret	0
$LN2@qt_metacas:
; Line 217
	lea	r8, OFFSET FLAT:?qt_meta_stringdata_xGLWidget@@3Uqt_meta_stringdata_xGLWidget_t@@B+480
	mov	rax, r9
	sub	r8, r9
	npad	5
$LL5@qt_metacas:
	movzx	edx, BYTE PTR [rax]
	movzx	ecx, BYTE PTR [rax+r8]
	sub	edx, ecx
	jne	SHORT $LN6@qt_metacas
	inc	rax
	test	ecx, ecx
	jne	SHORT $LL5@qt_metacas
$LN6@qt_metacas:
	test	edx, edx
	jne	SHORT $LN3@qt_metacas
; Line 218
	mov	rax, r10
; Line 220
	ret	0
$LN3@qt_metacas:
; Line 219
	mov	rdx, r9
	mov	rcx, r10
	rex_jmp	QWORD PTR __imp_?qt_metacast@QGLWidget@@UEAAPEAXPEBD@Z
?qt_metacast@xGLWidget@@UEAAPEAXPEBD@Z ENDP		; xGLWidget::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?metaObject@xGLWidget@@UEBAPEBUQMetaObject@@XZ
_TEXT	SEGMENT
this$ = 8
?metaObject@xGLWidget@@UEBAPEBUQMetaObject@@XZ PROC	; xGLWidget::metaObject, COMDAT
; File c:\xdynamics\xdynamics_gui\generatedfiles\release\moc_xglwidget.cpp
; Line 211
	mov	rcx, QWORD PTR [rcx+8]
	cmp	QWORD PTR [rcx+40], 0
	je	SHORT $LN3@metaObject
	rex_jmp	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@xGLWidget@@2UQMetaObject@@B ; xGLWidget::staticMetaObject
; Line 212
	ret	0
?metaObject@xGLWidget@@UEBAPEBUQMetaObject@@XZ ENDP	; xGLWidget::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Fg_vglew@@YAXXZ
text$yd	SEGMENT
??__Fg_vglew@@YAXXZ PROC				; `dynamic atexit destructor for 'g_vglew'', COMDAT
	ret	0
??__Fg_vglew@@YAXXZ ENDP				; `dynamic atexit destructor for 'g_vglew''
text$yd	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Eg_vglew@@YAXXZ
text$di	SEGMENT
??__Eg_vglew@@YAXXZ PROC				; `dynamic initializer for 'g_vglew'', COMDAT
; File c:\xdynamics\include\xdynamics_gui\xvglew.h
; Line 44
	sub	rsp, 40					; 00000028H
; Line 20
	call	QWORD PTR __imp_glewInit
; Line 44
	lea	rcx, OFFSET FLAT:??__Fg_vglew@@YAXXZ	; `dynamic atexit destructor for 'g_vglew''
; Line 21
	mov	BYTE PTR ?g_vglew@@3VxvGlew@@A, 1
; Line 44
	add	rsp, 40					; 00000028H
	jmp	atexit
??__Eg_vglew@@YAXXZ ENDP				; `dynamic initializer for 'g_vglew''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1xvGlew@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1xvGlew@@QEAA@XZ PROC					; xvGlew::~xvGlew, COMDAT
; File c:\xdynamics\include\xdynamics_gui\xvglew.h
; Line 30
	ret	0
??1xvGlew@@QEAA@XZ ENDP					; xvGlew::~xvGlew
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0xvGlew@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??0xvGlew@@QEAA@XZ PROC					; xvGlew::xvGlew, COMDAT
; File c:\xdynamics\include\xdynamics_gui\xvglew.h
; Line 19
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	BYTE PTR [rcx], 0
; Line 20
	call	QWORD PTR __imp_glewInit
; Line 22
	mov	rax, rbx
	mov	BYTE PTR [rbx], 1
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0xvGlew@@QEAA@XZ ENDP					; xvGlew::xvGlew
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.3\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 118
	mov	rax, QWORD PTR [rcx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
